---
title: "Unit 1 Readings: What is Learning Analytics?"
subtitle: "ECI 586 Intro to Learning Analytics"
author: "Dr. Shaun Kellogg"
date: "`r format(Sys.Date(),'%B %e, %Y')`"
format:
  html:
    toc: true
    toc-depth: 3
theme:
  light: simplex
  dark: cyborg
editor: visual
---

## READINGS

In addition to watching the Unit 1 intro video, this week you'll be required to read two chapters from [Learning Analytics Goes to School](https://catalog.lib.ncsu.edu/catalog/NCSU4862134) and find one additional journal article, presentation, website or other scholarly resource to help address our discussion questions for the week.

### Learning Analytics Goes to School

-   Chapter 1: Introduction
-   Chapter 2: Data Used in Educational Data-Intensive Research

### Self-Selected Resource 

Use the [NCSU Library](https://www.lib.ncsu.edu/#articles), [Google Scholar](https://scholar.google.com/) or search engine of your choice to locate a journal article, presentation, website or other scholarly resource that includes the key words, "learning analytics" and addresses a topic of interest to you. Your selection should also address one or more of the discussion topics/questions provided below. In addition, you are welcome to find less formal resources such as videos or shorter online articles to share with the class and that help us better understand this week's topics for discussion.

## DISCUSSION

In lieu of the peer interaction and discussion of course materials that normally take place "in class", you'll be asked to log in this week and engage with other members of our learning community through the course discussion forum. To help guide our discussions, we will collectively address a set of guiding questions provided in each forum. You are also welcome to add your own topics or questions for the class to discuss.

With the exception of the Self-Selected resource, you are not required to post to every thread or address every question raised in the discussions, particularly if you feel others in the class have thoroughly addressed the topic or questions. Our primary goal for these discussions is to collectively build our understanding of this week's topics through back-and-forth dialogue and avoid a "collective monologue" in which we see 20 variations of effectively the same post.

### Guiding Questions

#### Chapter 1: Introduction

Reflecting on your course text and self-selected reading, answer one or more of the following questions:

1.  How is LA defined? What is your interpretation of this definition?
2.  What are some similarities and differences when compared to fields such as Educational Data Mining (EDM), Data Science, or Business Analytics?
3.  What is a core characteristic or feature of learning analytics that stands out to you? 
4.  From where does does learning analytics take its historical roots?
5.  What are some of the most common uses of learning analytics?
6.  What questions do you still have about learning analytics?

#### Chapter 2: Data Used in Educational Data-Intensive Research

Reflecting on the course text and your self-selected reading, answer one or more of the following questions:

1.  Among the types of educational data used in data-intensive research, with which are you most/least familiar? Most/least interested in working with?
2.  How might these sources of data be used to better understand or improve the educational contexts in which you work or are interested in researching?
3.  What are challenges typically faced with these types of data? What challenges or opportunities do you anticipate for yourself?
4.  How might learning analytics be used to better understand a dataset or educational context of personal or professional interest to you?
5.  How is the data intensive workflow similar to or different than other data analysis processes you may have come across before?
6.  What questions do you still have about data used in data-intensive research like learning analytics?

#### Self-Selected Resource

Provide a brief overview of your self-selected resource that includes the following:

-   APA Citation (note: this can be easily [retrieved via Google Scholar](https://libanswers.ucmerced.edu/faq/95935))
-   What was the **purpose** of your article?
-   How was Learning Analytics **defined** and/or characterized?
-   What **data source(s)** were analyzed or discussed?
-   How, if at all, did your article touch upon the **application(s)** of LA to "understand and improve learning and the contexts in which learning occurs?"
-   Did your selection address any **ethical or legal considerations** of LA?

## ASSESSMENT

### Grading

Grading for this week is fairly lenient, provided that it's clear from your posts that you've done the required readings. Readings and discussion for each unit are worth 6 points and judged based on quantity and quality of your posts.

In term of **quantity** (3 points), you'll be expected to add at least 3 posts in addition to an overview of your the Selected Resource. Your initial post should be shared by Friday to help facilitate discussion.

In terms of **quality** (3 points), your posts over the next week should provide new or insightful contributions to the division questions or topics. There is no requisite for the length of each posting, and I strongly recommend taking a look at Table 1 of [Gao's productive online discussion model](https://github.com/sbkellogg/eci-586/blob/main/unit-1/lit/Gao-productive-discussion.pdf) (summarized below) for ways to contribute to the conversation.

At minimum, your collective posts should also help us interpret or elaborate on discussion topics, questions, or ideas others have shared by "making connection to the learning materials" and should reference at some point the required video, course text and your self-selected resource.

### Productive Online Discussion Model

#### **Disposition 1: Discuss to Comprehend**

Actively engage in such cognitive processes as interpretation, elaboration, **making connections to** prior knowledge.

-   Interpreting or elaborating the ideas by making connection to the **learning materials**
-   Interpreting or elaborating the ideas by making connection to **personal experience**
-   Interpreting or elaborating the ideas by making connection to other **ideas, sources, or references**

#### **Disposition 2: Discuss to Critique**

Carefully **examine other people's views**, and be sensitive and analytical to conflicting views.

-   Building or **adding new insights or ideas** to others' posts
-   **Challenging ideas** in the texts
-   Challenging ideas in others' posts

#### **Disposition 3: Discuss to Construct Knowledge**

Actively **negotiate meanings**, and be ready to reconsider, refine and sometimes revise their thinking.

-   **Comparing views** from the texts or others' posts
-   Facilitating thinking and discussions by **raising questions**
-   Refining and **revising one's own view** based on the texts or others' posts

#### **Disposition 4: Discuss to Share Improved Understanding**

Actively **synthesize knowledge** and explicitly express improved understanding based on a review of previous discussions.

-   **Summarizing personal learning** experiences of online discussions
-   **Synthesizing content** of discussion
-   **Generating new topics** based on a review of previous discussions
