---
title: "Unit 2 Readings: Methods Used & Responsible Use"
subtitle: "ECI 586 Intro to Learning Analytics"
author: "Dr. Shaun Kellogg"
date: today
format:
  html:
    toc: true
    toc-depth: 3
theme:
  light: simplex
  dark: cyborg
editor: visual
bibliography: lit/references.bib
---

## OVERVIEW

The primary goal of our Unit 2 readings and discussion is to develop a better understanding of the legal and ethical considerations surrounding learning analytics and as well the three major influences on the collaborative data-intensive improvement (CDI) model introduced in Unit 1. Chapter 4 of LA Goes to School [@krumm2018] provides a deep dive to the legal requirements imposed by federal and state governments, and recommendations for the responsible and ethical use of student data. Chapter 5 then provides a overview of datadriven decision making, emerging models of how researchers and education practitioners can engage in collaborative research, and the rapidly expanding fields of educational data mining and learning analytics.

## READINGS

This week you'll be required to read Chapter 4 from Learning Analytics Goes to School [@krumm2018], an excellent article on using ML to predict student outcomes by some colleagues at Duke and Chapel Hill [@arizmendi2022predicting], and find one additional journal article, conference presentation, or scholarly resource to help address our discussion questions for the week.

### Instructor-Selected

-   Krumm, A., Means, B., & Bienkowski, M. (2018). Chapter 4: Legal and Ethical Issues in Using Educational Data. *Learning analytics goes to school: A collaborative approach to improving education*. Routledge.
-   Arizmendi, C. J., Bernacki, M. L., Raković, M., Plumley, R. D., Urban, C. J., Panter, A. T., ... & Gates, K. M. (2022). Predicting student outcomes using digital logs of learning behaviors: Review, current standards, and suggestions for future work. Behavior research methods, 1-29. <https://link.springer.com/article/10.3758/s13428-022-01939-9>

### Self-Selected Resource

Use the [NCSU Library](https://www.lib.ncsu.edu/#articles), [Google Scholar](https://scholar.google.com/) or search engine of your choice to locate a journal article, presentation, website or other scholarly resource that addresses a topic of interest and includes two or more of the following terms:

-   learning analytics
-   predictive analytics
-   machine learning
-   algorithmic bias
-   data ethics
-   data privacy

Your selection should also address one or more of the discussion topics/questions provided below. In addition, you are welcome to find less formal resources such as videos or shorter online articles to share with the class and that help us better understand this week's topics for discussion.

One optional but highly recommended read is Stewart's @stewart2019actual very accessible post on Medium outlining the differences between machine learning and statistics. In essence, he notes that:

> The purpose of (supervised) machine learning is obtaining a model that can make repeatable predictions. We typically do not care if the model is interpretable... machine learning is all about results. Whereas, statistical modeling is more about finding relationships between variables and the significance of those relationships.

You are mare than welcome

-   Stewart, M. (2019). The actual difference between statistics and machine learning. Towards Data Science, 24(3), 19. <https://towardsdatascience.com/the-actual-difference-between-statistics-and-machine-learning-64b49f07ea3>

## DISCUSSION

In lieu of the peer interaction and discussion of course materials that normally take place "in class", you'll be asked to log in this week and engage with other members of our learning community through the course discussion forum. To help guide our discussions, we will collectively address a set of guiding questions provided in each forum. You are also welcome to add your own topics or questions for the class to discuss.

With the exception of the self-selected resource, you are not required to post to every thread or address every question raised in the discussions, particularly if you feel others in the class have thoroughly addressed the topic or questions. Our primary goal for these discussions is to collectively build our understanding of this week's topics through back-and-forth dialogue.

### Guiding Questions

#### Legal and Ethical Issues in Using Educational Data

Reflecting on the course text and your self-selected reading, answer one or more of the following questions:

-   What is one **potential harm** arising from the proliferation of educational data and what laws and/or ethical principles have been developed to address it?
-   What are some of the similarities and differences between **laws and ethical guidelines** that have emerged to address issues surrounding student data?
-   During what step of the **data-intensive research workflow** might you need to address a legal or ethical issue associated with student data?
-   What is an example of **algorithmic bias** that might emerge in a learning context and how might education researchers address it?
-   What **questions** do you still have about legal or ethical consideration for data-intensive research methods like learning analytics?

#### Machine Learning in Education

Reflecting on the course text and your self-selected reading, answer one or more of the following questions:

-   How do the **methods and goals of machine learning** (supervised or unsupervised) differ from more traditional statistical methods in education?
-   What are some of the **advantages and disadvantages** of using machine learning in educational research?
-   What are some **common predictor variables** or "features" used in machine learning models for predicting outcomes?
-   What **types of machine learning algorithms** are commonly used in predicting learning outcomes?
-   **How do these algorithms differ** from each other and from models used in traditional statistics?
-   What **questions** do you still have about machine learning and it's applications in learning analytics?

#### Self-Selected Resource

Provide a brief overview of your self-selected resource that includes the following:

-   APA Citation (note: this can be easily [retrieved via Google Scholar](#0))
-   What was the **purpose** of your article?
-   What **data source(s),** if any, were analyzed or discussed?
-   What data-intensive research **workflows** steps, if any, were described by your selection?
-   Who were the intended **beneficiaries** of the work and what "change ideas" might the result imply for them?
-   How, if at all, did your resource touch upon the **application(s)** of these methods and phases to "understand and improve learning and the contexts in which learning occurs?"
-   Did your selection address any **ethical or legal considerations** of LA?

## ASSESSMENT

### Grading

Grading for this week is fairly lenient, provided that it's clear from your posts that you've done the required readings. Readings and discussion for each unit are worth 6 points and judged based on quantity and quality of your posts.

In term of **quantity** (3 points), you'll be expected to add at least 3 posts in addition to an overview of your Selected Resource. Your initial post should be shared by Friday to help facilitate discussion.

In terms of **quality** (3 points), your posts over the next week should provide new or insightful contributions to the division questions or topics. There is no requisite for the length of each posting, and I strongly recommend taking a look at Table 1 of [Gao's productive online discussion model](https://github.com/sbkellogg/eci-586/blob/main/unit-1/lit/Gao-productive-discussion.pdf) (summarized below) for ways to contribute to the conversation.

At minimum, your collective posts should also help us interpret or elaborate on discussion topics, questions, or ideas others have shared by "making connection to the learning materials" and should reference at some point the required video, course text and your self-selected resource.

### Productive Online Discussion Model

#### **Disposition 1: Discuss to Comprehend**

Actively engage in such cognitive processes as interpretation, elaboration, **making connections to** prior knowledge.

-   Interpreting or elaborating the ideas by making connection to the **learning materials**
-   Interpreting or elaborating the ideas by making connection to **personal experience**
-   Interpreting or elaborating the ideas by making connection to other **ideas, sources, or references**

#### **Disposition 2: Discuss to Critique**

Carefully **examine other people's views**, and be sensitive and analytical to conflicting views.

-   Building or **adding new insights or ideas** to others' posts
-   **Challenging ideas** in the texts
-   Challenging ideas in others' posts

#### **Disposition 3: Discuss to Construct Knowledge**

Actively **negotiate meanings**, and be ready to reconsider, refine and sometimes revise their thinking.

-   **Comparing views** from the texts or others' posts
-   Facilitating thinking and discussions by **raising questions**
-   Refining and **revising one's own view** based on the texts or others' posts

#### **Disposition 4: Discuss to Share Improved Understanding**

Actively **synthesize knowledge** and explicitly express improved understanding based on a review of previous discussions.

-   **Summarizing personal learning** experiences of online discussions
-   **Synthesizing content** of discussion
-   **Generating new topics** based on a review of previous discussions

## REFERENCES
