<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Dr.&nbsp;Shaun Kellogg">
<meta name="dcterms.date" content="2023-09-29">

<title>Unit 2 Case Study: Identifying At-Risk Students</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="unit-2-ml-case-study-key_files/libs/clipboard/clipboard.min.js"></script>
<script src="unit-2-ml-case-study-key_files/libs/quarto-html/quarto.js"></script>
<script src="unit-2-ml-case-study-key_files/libs/quarto-html/popper.min.js"></script>
<script src="unit-2-ml-case-study-key_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="unit-2-ml-case-study-key_files/libs/quarto-html/anchor.min.js"></script>
<link href="unit-2-ml-case-study-key_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="unit-2-ml-case-study-key_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="unit-2-ml-case-study-key_files/libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="unit-2-ml-case-study-key_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="unit-2-ml-case-study-key_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="unit-2-ml-case-study-key_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="unit-2-ml-case-study-key_files/libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#prepare" id="toc-prepare" class="nav-link active" data-scroll-target="#prepare">1. PREPARE</a>
  <ul>
  <li><a href="#a.-conceptual-focus" id="toc-a.-conceptual-focus" class="nav-link" data-scroll-target="#a.-conceptual-focus">1a. Conceptual Focus</a>
  <ul class="collapse">
  <li><a href="#research-question" id="toc-research-question" class="nav-link" data-scroll-target="#research-question">Research Question</a></li>
  <li><a href="#reading-1-statistical-modeling-the-two-cultures" id="toc-reading-1-statistical-modeling-the-two-cultures" class="nav-link" data-scroll-target="#reading-1-statistical-modeling-the-two-cultures">Reading 1: Statistical modeling: The two cultures</a></li>
  <li><a href="#your-turn" id="toc-your-turn" class="nav-link" data-scroll-target="#your-turn"><strong>👉 Your Turn</strong> <strong>⤵</strong></a></li>
  </ul></li>
  <li><a href="#b.-load-libraries" id="toc-b.-load-libraries" class="nav-link" data-scroll-target="#b.-load-libraries">1b. Load Libraries</a>
  <ul class="collapse">
  <li><a href="#tidymodels" id="toc-tidymodels" class="nav-link" data-scroll-target="#tidymodels">tidymodels 📦</a></li>
  <li><a href="#your-turn-1" id="toc-your-turn-1" class="nav-link" data-scroll-target="#your-turn-1"><span style="color: green;"><strong>Your Turn</strong></span> <strong>⤵</strong></a></li>
  </ul></li>
  <li><a href="#c.-import-inspect-data" id="toc-c.-import-inspect-data" class="nav-link" data-scroll-target="#c.-import-inspect-data">1c. Import &amp; Inspect Data</a>
  <ul class="collapse">
  <li><a href="#your-turn-2" id="toc-your-turn-2" class="nav-link" data-scroll-target="#your-turn-2"><span style="color: green;"><strong>Your Turn</strong></span> <strong>⤵</strong></a></li>
  </ul></li>
  </ul></li>
  <li><a href="#wrangle" id="toc-wrangle" class="nav-link" data-scroll-target="#wrangle">2. WRANGLE</a>
  <ul>
  <li><a href="#a.-create-outcome-variable" id="toc-a.-create-outcome-variable" class="nav-link" data-scroll-target="#a.-create-outcome-variable">a. Create Outcome Variable</a></li>
  <li><a href="#b.-convert-to-factors" id="toc-b.-convert-to-factors" class="nav-link" data-scroll-target="#b.-convert-to-factors">b. Convert to Factors</a></li>
  <li><a href="#c.-select-predictors" id="toc-c.-select-predictors" class="nav-link" data-scroll-target="#c.-select-predictors">c.&nbsp;Select Predictors</a>
  <ul class="collapse">
  <li><a href="#your-turn-3" id="toc-your-turn-3" class="nav-link" data-scroll-target="#your-turn-3"><span style="color: green;"><strong>Your Turn</strong></span> <strong>⤵</strong></a></li>
  </ul></li>
  </ul></li>
  <li><a href="#explore" id="toc-explore" class="nav-link" data-scroll-target="#explore">3. Explore</a>
  <ul>
  <li><a href="#a.-count-proportions" id="toc-a.-count-proportions" class="nav-link" data-scroll-target="#a.-count-proportions">a. Count proportions</a>
  <ul class="collapse">
  <li><a href="#your-turn-4" id="toc-your-turn-4" class="nav-link" data-scroll-target="#your-turn-4"><span style="color: green;"><strong>Your Turn</strong></span> <strong>⤵</strong></a></li>
  <li><a href="#remove-cases" id="toc-remove-cases" class="nav-link" data-scroll-target="#remove-cases">Remove Cases</a></li>
  <li><a href="#your-turn-5" id="toc-your-turn-5" class="nav-link" data-scroll-target="#your-turn-5"><span style="color: green;"><strong>Your Turn</strong></span> <strong>⤵</strong></a></li>
  </ul></li>
  <li><a href="#b.-feature-engineering" id="toc-b.-feature-engineering" class="nav-link" data-scroll-target="#b.-feature-engineering">b. Feature Engineering</a>
  <ul class="collapse">
  <li><a href="#student-performance-features" id="toc-student-performance-features" class="nav-link" data-scroll-target="#student-performance-features">Student Performance Features</a></li>
  <li><a href="#group-slice-data" id="toc-group-slice-data" class="nav-link" data-scroll-target="#group-slice-data">Group &amp; Slice Data</a></li>
  <li><a href="#your-turn-6" id="toc-your-turn-6" class="nav-link" data-scroll-target="#your-turn-6"><span style="color: green;">Your Turn</span> ⤵</a></li>
  <li><a href="#create-new-variables" id="toc-create-new-variables" class="nav-link" data-scroll-target="#create-new-variables">Create New Variables</a></li>
  <li><a href="#your-turn-7" id="toc-your-turn-7" class="nav-link" data-scroll-target="#your-turn-7"><span style="color: green;">Your Turn</span> ⤵</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#model" id="toc-model" class="nav-link" data-scroll-target="#model">4. MODEL</a>
  <ul>
  <li><a href="#a.-split-data" id="toc-a.-split-data" class="nav-link" data-scroll-target="#a.-split-data">a. Split Data</a>
  <ul class="collapse">
  <li><a href="#your-turn-8" id="toc-your-turn-8" class="nav-link" data-scroll-target="#your-turn-8"><span style="color: green;"><strong>Your Turn</strong></span> <strong>⤵</strong></a></li>
  <li><a href="#create-a-training-and-test-set" id="toc-create-a-training-and-test-set" class="nav-link" data-scroll-target="#create-a-training-and-test-set">Create a training and test set</a></li>
  <li><a href="#your-turn-9" id="toc-your-turn-9" class="nav-link" data-scroll-target="#your-turn-9"><span style="color: green;"><strong>Your Turn</strong></span> <strong>⤵</strong></a></li>
  </ul></li>
  <li><a href="#b.-create-a-recipe" id="toc-b.-create-a-recipe" class="nav-link" data-scroll-target="#b.-create-a-recipe">b. <strong>Create a Recipe</strong></a>
  <ul class="collapse">
  <li><a href="#add-a-formula" id="toc-add-a-formula" class="nav-link" data-scroll-target="#add-a-formula">Add a formula</a></li>
  <li><a href="#create-dummy-variables" id="toc-create-dummy-variables" class="nav-link" data-scroll-target="#create-dummy-variables">Create Dummy Variables</a></li>
  <li><a href="#create-a-kitchen-sink-recipe" id="toc-create-a-kitchen-sink-recipe" class="nav-link" data-scroll-target="#create-a-kitchen-sink-recipe">Create a kitchen sink recipe</a></li>
  </ul></li>
  <li><a href="#c.-fit-a-logistic-regression-model" id="toc-c.-fit-a-logistic-regression-model" class="nav-link" data-scroll-target="#c.-fit-a-logistic-regression-model">c.&nbsp;Fit a Logistic Regression Model</a>
  <ul class="collapse">
  <li><a href="#start-your-engine" id="toc-start-your-engine" class="nav-link" data-scroll-target="#start-your-engine">Start your engine</a></li>
  <li><a href="#add-to-workflow" id="toc-add-to-workflow" class="nav-link" data-scroll-target="#add-to-workflow">Add to workflow</a></li>
  <li><a href="#fit-model-to-training-set" id="toc-fit-model-to-training-set" class="nav-link" data-scroll-target="#fit-model-to-training-set">Fit model to training set</a></li>
  <li><a href="#test-the-model" id="toc-test-the-model" class="nav-link" data-scroll-target="#test-the-model">Test the model</a></li>
  <li><a href="#your-turn-10" id="toc-your-turn-10" class="nav-link" data-scroll-target="#your-turn-10"><span style="color: green;"><strong>Your Turn</strong></span> <strong>⤵</strong></a></li>
  </ul></li>
  <li><a href="#d.-check-model-accuracy" id="toc-d.-check-model-accuracy" class="nav-link" data-scroll-target="#d.-check-model-accuracy">d.&nbsp;Check model accuracy</a>
  <ul class="collapse">
  <li><a href="#your-turn-11" id="toc-your-turn-11" class="nav-link" data-scroll-target="#your-turn-11"><span style="color: green;"><strong>Your Turn</strong></span> <strong>⤵</strong></a></li>
  </ul></li>
  <li><a href="#d.-fit-a-random-forest-model" id="toc-d.-fit-a-random-forest-model" class="nav-link" data-scroll-target="#d.-fit-a-random-forest-model">d.&nbsp;Fit a Random Forest Model</a>
  <ul class="collapse">
  <li><a href="#your-turn-12" id="toc-your-turn-12" class="nav-link" data-scroll-target="#your-turn-12"><span style="color: green;"><strong>Your Turn</strong></span> <strong>⤵</strong></a></li>
  </ul></li>
  </ul></li>
  <li><a href="#communicate" id="toc-communicate" class="nav-link" data-scroll-target="#communicate">5. COMMUNICATE</a>
  <ul>
  <li><a href="#congratulations" id="toc-congratulations" class="nav-link" data-scroll-target="#congratulations">Congratulations!</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Unit 2 Case Study: Identifying At-Risk Students</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Dr.&nbsp;Shaun Kellogg </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 29, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="prepare" class="level2">
<h2 class="anchored" data-anchor-id="prepare">1. PREPARE</h2>
<p>In Unit 2, we pick up where we left off and learn to apply some basic machine learning techniques to help us understand how a predictive model might be developed and tested as part of an early warning system to identify students at risk of failing. Specifically, we will make a very crude first attempt at developing a testing a logistic regression and a random forest model that can (we hope!) accurately predict whether a student will pass or fail and online course. Unlike Unit 1, where we were interested in identifying factors from data collected throughout the course that might help explain why students earned the grade they did, we are instead interested identifying students who may be at risk before it is too late to intervene.</p>
<section id="a.-conceptual-focus" class="level3">
<h3 class="anchored" data-anchor-id="a.-conceptual-focus">1a. Conceptual Focus</h3>
<p>Conceptually, in this unit we focus on prediction, the primary goal of supervised machine learning, and how it differs from the goals of description or explanation, a goal of traditional statistical methods. The reading introduced below focuses on this distinction between prediction and description or explanation. It is one of the most widely-read papers in machine learning and articulates how machine learning differs from other kinds of statistical models. Breiman describes the difference in terms of <em>data modeling</em> (models for description and explanation) and <em>algorithmic modeling</em> (what we call prediction or machine learning models).</p>
<section id="research-question" class="level4">
<h4 class="anchored" data-anchor-id="research-question">Research Question</h4>
<p>Technically, we’ll focus on the core parts of doing a machine learning analysis in R. We’ll use the {<a href="https://www.tidymodels.org/">tidymodels</a>} set of R packages (add-ons) to do so. However, to help anchor our analysis and provide us with some direction, we’ll focus on the following research question as we explore this new:</p>
<blockquote class="blockquote">
<p>How well can we predict students who are at risk of failing a course?</p>
</blockquote>
</section>
<section id="reading-1-statistical-modeling-the-two-cultures" class="level4">
<h4 class="anchored" data-anchor-id="reading-1-statistical-modeling-the-two-cultures">Reading 1: Statistical modeling: The two cultures</h4>
<p><img src="img/breiman.png" class="img-fluid" style="width:50.0%"></p>
<p>Breiman, L. (2001). Statistical modeling: The two cultures (with comments and a rejoinder by the author). <em>Statistical Science, 16</em>(3), 199-231. <a href="https://projecteuclid.org/journals/statistical-science/volume-16/issue-3/Statistical-Modeling--The-Two-Cultures-with-comments-and-a/10.1214/ss/1009213726.pdf" class="uri">https://projecteuclid.org/journals/statistical-science/volume-16/issue-3/Statistical-Modeling--The-Two-Cultures-with-comments-and-a/10.1214/ss/1009213726.pdf</a></p>
<p><strong>Abstract</strong></p>
<p>There are two cultures in the use of statistical modeling to reach conclusions from data. One assumes that the data are generated by a given stochastic data model. The other uses algorithmic models and treats the data mechanism as unknown. The statistical community has been committed to the almost exclusive use of data models. This commitment has led to irrelevant theory, questionable conclusions, and has kept statisticians from working on a large range of interesting current problems. Algorithmic modeling, both in theory and practice, has developed rapidly in fields outside statistics. It can be used both on large complex data sets and as a more accurate and informative alternative to data modeling on smaller data sets. If our goal as a field is to use data to solve problems, then we need to move away from exclusive dependence on data models and adopt a more diverse set of tools.</p>
</section>
<section id="your-turn" class="level4">
<h4 class="anchored" data-anchor-id="your-turn"><strong>👉 Your Turn</strong> <strong>⤵</strong></h4>
<p>Open up the article and take quick scan of the article and note below an observation or question you have about the article.</p>
<ul>
<li>YOUR RESPONSE HERE</li>
</ul>
</section>
</section>
<section id="b.-load-libraries" class="level3">
<h3 class="anchored" data-anchor-id="b.-load-libraries">1b. Load Libraries</h3>
<section id="tidymodels" class="level4">
<h4 class="anchored" data-anchor-id="tidymodels">tidymodels 📦</h4>
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><a href="https://www.tidymodels.org"><img src="img/tidymodels.svg" class="img-fluid figure-img" style="width:30.0%"></a></p>
</figure>
</div>
<p>The <a href="https://www.tidymodels.org">tidymodels</a> package is a “meta-package” for modeling and statistical analysis that shares the underlying design philosophy, grammar, and data structures of the <a href="https://www.tidyverse.org/">tidyverse</a>. It includes a core set of packages that are loaded on startup and contains tools for:</p>
<ul>
<li>data splitting and pre-processing;</li>
<li>model selection, tuning, and evaluation;</li>
<li>feature selection and variable importance estimation;</li>
<li>as well as other functionality.</li>
</ul>
</section>
<section id="your-turn-1" class="level4">
<h4 class="anchored" data-anchor-id="your-turn-1"><span style="color: green;"><strong>Your Turn</strong></span> <strong>⤵</strong></h4>
<p>In addition to the {tidymodels} package, we’ll also be using the {tidyverse} packages we learned about in Unit 1, and the {ranger} package we’ll be using for our random forest model in Part 4.</p>
<p>Use the code chunk below to load these three packages:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidymodels)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages ────────────────────────────────────── tidymodels 1.1.0 ──</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>✔ broom        1.0.5     ✔ recipes      1.0.6
✔ dials        1.2.0     ✔ rsample      1.1.1
✔ dplyr        1.1.2     ✔ tibble       3.2.1
✔ ggplot2      3.4.2     ✔ tidyr        1.3.0
✔ infer        1.0.4     ✔ tune         1.1.1
✔ modeldata    1.1.0     ✔ workflows    1.1.3
✔ parsnip      1.1.0     ✔ workflowsets 1.0.1
✔ purrr        1.0.1     ✔ yardstick    1.2.0</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ───────────────────────────────────────── tidymodels_conflicts() ──
✖ purrr::discard() masks scales::discard()
✖ dplyr::filter()  masks stats::filter()
✖ dplyr::lag()     masks stats::lag()
✖ recipes::step()  masks stats::step()
• Learn how to get started at https://www.tidymodels.org/start/</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ forcats   1.0.0     ✔ readr     2.1.4
✔ lubridate 1.9.2     ✔ stringr   1.5.0</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ readr::col_factor() masks scales::col_factor()
✖ purrr::discard()    masks scales::discard()
✖ dplyr::filter()     masks stats::filter()
✖ stringr::fixed()    masks recipes::fixed()
✖ dplyr::lag()        masks stats::lag()
✖ readr::spec()       masks yardstick::spec()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ranger)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="c.-import-inspect-data" class="level3">
<h3 class="anchored" data-anchor-id="c.-import-inspect-data">1c. Import &amp; Inspect Data</h3>
<p>For this case study, we will again be working again with data from the online science courses introduced in Unit 1. This data is located in the data folder and named <code>processed-data.csv</code>. Fortunately, our data has already been largely wrangled. This will save us quite a bit of time, which we’ll need to help wrap our heads around some supervised machine learning basics.</p>
<p>Run the code chunk below to read this data into your R environment as an object named <code>processed_data</code> and let’s take a quick look at data we may use in our predictive model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>processed_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/processed-data.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 603 Columns: 17
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (2): course_id, gender
dbl (15): student_id, final_grade, course_interest, perceived_competence, ut...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>processed_data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 603 × 17
   student_id course_id  final_grade gender course_interest perceived_competence
        &lt;dbl&gt; &lt;chr&gt;            &lt;dbl&gt; &lt;chr&gt;            &lt;dbl&gt;                &lt;dbl&gt;
 1      43146 FrScA-S21…        93.5 M                  5                    4.5
 2      44638 OcnA-S116…        81.7 F                  4.2                  3.5
 3      47448 FrScA-S21…        88.5 M                  5                    4  
 4      47979 OcnA-S216…        81.9 M                  5                    3.5
 5      48797 PhysA-S11…        84   F                  3.8                  3.5
 6      51943 FrScA-S21…        NA   F                  4.6                  4  
 7      52326 AnPhA-S21…        83.6 M                  5                    3.5
 8      52446 PhysA-S11…        97.8 F                  3                    3  
 9      53447 FrScA-S11…        96.1 F                  4.2                  3  
10      53475 FrScA-S11…        NA   M                 NA                   NA  
# ℹ 593 more rows
# ℹ 11 more variables: utility_value &lt;dbl&gt;, q1 &lt;dbl&gt;, q2 &lt;dbl&gt;, q3 &lt;dbl&gt;,
#   q4 &lt;dbl&gt;, q5 &lt;dbl&gt;, q6 &lt;dbl&gt;, q7 &lt;dbl&gt;, q8 &lt;dbl&gt;, q9 &lt;dbl&gt;, q10 &lt;dbl&gt;</code></pre>
</div>
</div>
<section id="your-turn-2" class="level4">
<h4 class="anchored" data-anchor-id="your-turn-2"><span style="color: green;"><strong>Your Turn</strong></span> <strong>⤵</strong></h4>
<p>In addition to students’ gender and their pre-course survey responses assessing three aspects of student motivation, we will also incorporate gradebook data collected during the course that we will also use to help “train” a predictive model for identifying students at risk of failing.</p>
<p>Use the code chunk below to read in the .csv file named “grade-book.csv” located in the data folder, assign to a new object named <code>grade_book</code>, and use a method of your choosing to answer the questions that follow:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Your Code Here</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>grade_book <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/grade-book.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 29711 Columns: 5
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (2): course_id, gradebook_item
dbl (3): student_id, points_possible, points_earned

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>grade_book</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 29,711 × 5
   course_id     student_id gradebook_item         points_possible points_earned
   &lt;chr&gt;              &lt;dbl&gt; &lt;chr&gt;                            &lt;dbl&gt;         &lt;dbl&gt;
 1 AnPhA-S116-01      60186 POINTS EARNED &amp; TOTAL…               5          4.05
 2 AnPhA-S116-01      60186 WORK ATTEMPTED                      30         24   
 3 AnPhA-S116-01      60186 0.1: Message Your Ins…             105         71.7 
 4 AnPhA-S116-01      60186 0.2: Intro Assignment…             140        141.  
 5 AnPhA-S116-01      60186 0.3: Intro Assignment…               5          5   
 6 AnPhA-S116-01      60186 1.1: Quiz                            5          4   
 7 AnPhA-S116-01      60186 1.2: Quiz                           20         NA   
 8 AnPhA-S116-01      60186 1.3: Create a Living …              50         50   
 9 AnPhA-S116-01      60186 1.3: Create a Living …              10         NA   
10 AnPhA-S116-01      60186 1.4: Negative Feedbac…              50         44   
# ℹ 29,701 more rows</code></pre>
</div>
</div>
<ol type="1">
<li><p>How many observations and variables are in our <code>grade_book</code> dataset? And roughly how many observations are there per student?</p>
<ul>
<li>YOUR RESPONSE HERE</li>
</ul></li>
<li><p>How might this data be used in our model to help predict student at risk of failing the course?</p>
<ul>
<li>YOUR RESPONSE HERE</li>
</ul></li>
<li><p>What else do you notice about this data set?</p>
<ul>
<li>YOUR RESPONSE HERE</li>
</ul></li>
</ol>
</section>
</section>
</section>
<section id="wrangle" class="level2">
<h2 class="anchored" data-anchor-id="wrangle">2. WRANGLE</h2>
<p>In general, data wrangling involves some combination of cleaning, reshaping, transforming, and merging data (Wickham &amp; Grolemund, 2017). The importance of data wrangling is difficult to overstate, as it involves the initial steps of going from raw data to a dataset that can be explored and modeled (Krumm et al, 2018). In Part 2, we focus on the the following wrangling processes to:</p>
<ol type="a">
<li><p><strong>Create an Outcome Variable</strong>. We create a binary variable outcome we are interested in predicting, i.e.&nbsp;pass/fail.</p></li>
<li><p><strong>Convert Character Stings to Factors.</strong> We convert variables stored as character strings to factors expected by our models.</p></li>
<li><p><strong>Select Predictors.</strong> We narrow down our data set to specific predictors of interest.</p></li>
</ol>
<section id="a.-create-outcome-variable" class="level3">
<h3 class="anchored" data-anchor-id="a.-create-outcome-variable">a. Create Outcome Variable</h3>
<p>Since we are interested in developing a predictive model that can predict whether a student is at risk of failing a course, and so we can intervene before that happens, we need an outcome variable that let’s us know if they have either passed or failed.</p>
<p>Let’s combine the hopefully familiar <code>mutate()</code> function with the <code>if_else()</code> function also from the {dplyr} package to create a new variable called <code>at_risk</code> which indicates “no” for students whose <code>final_grade</code> is greater than or equal to 66.7% (NC State’s cutoff for a D-) and “yes” if it is not.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>course_data <span class="ot">&lt;-</span> processed_data <span class="sc">%&gt;%</span> </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">at_risk =</span> <span class="fu">if_else</span>(final_grade <span class="sc">&gt;=</span> <span class="fl">66.7</span>, <span class="st">"no"</span>, <span class="st">"yes"</span>)) </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>course_data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 603 × 18
   student_id course_id  final_grade gender course_interest perceived_competence
        &lt;dbl&gt; &lt;chr&gt;            &lt;dbl&gt; &lt;chr&gt;            &lt;dbl&gt;                &lt;dbl&gt;
 1      43146 FrScA-S21…        93.5 M                  5                    4.5
 2      44638 OcnA-S116…        81.7 F                  4.2                  3.5
 3      47448 FrScA-S21…        88.5 M                  5                    4  
 4      47979 OcnA-S216…        81.9 M                  5                    3.5
 5      48797 PhysA-S11…        84   F                  3.8                  3.5
 6      51943 FrScA-S21…        NA   F                  4.6                  4  
 7      52326 AnPhA-S21…        83.6 M                  5                    3.5
 8      52446 PhysA-S11…        97.8 F                  3                    3  
 9      53447 FrScA-S11…        96.1 F                  4.2                  3  
10      53475 FrScA-S11…        NA   M                 NA                   NA  
# ℹ 593 more rows
# ℹ 12 more variables: utility_value &lt;dbl&gt;, q1 &lt;dbl&gt;, q2 &lt;dbl&gt;, q3 &lt;dbl&gt;,
#   q4 &lt;dbl&gt;, q5 &lt;dbl&gt;, q6 &lt;dbl&gt;, q7 &lt;dbl&gt;, q8 &lt;dbl&gt;, q9 &lt;dbl&gt;, q10 &lt;dbl&gt;,
#   at_risk &lt;chr&gt;</code></pre>
</div>
</div>
</section>
<section id="b.-convert-to-factors" class="level3">
<h3 class="anchored" data-anchor-id="b.-convert-to-factors">b. Convert to Factors</h3>
<p>While inspecting the data, you may have noticed that one of our predictors of interest and our <code>at_risk</code> outcome variable are stored as character &lt;chr&gt; data types. For creating models, it is better to have qualitative variables like <code>gender</code> and <code>at_risk</code> encoded as factors instead of character strings. Factors store data as categorical variables, each with its own levels. Because categorical variables are used in statistical models differently than continuous variables, storing these data as factors ensures that the modeling functions will treat them correctly.</p>
<p>To do so, we once again use the <code>mutate()</code> function but instead of creating a new variable, we will use the <code>as_factor()</code> function to convert <code>gender</code> and <code>at_risk</code> from a character to a factor and save it as a variable of the same name, effectively replacing the old variables with new ones:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>course_data <span class="ot">&lt;-</span> course_data <span class="sc">|&gt;</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">gender =</span> <span class="fu">as_factor</span>(gender), </span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">at_risk =</span> <span class="fu">as_factor</span>(at_risk))</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>course_data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 603 × 18
   student_id course_id  final_grade gender course_interest perceived_competence
        &lt;dbl&gt; &lt;chr&gt;            &lt;dbl&gt; &lt;fct&gt;            &lt;dbl&gt;                &lt;dbl&gt;
 1      43146 FrScA-S21…        93.5 M                  5                    4.5
 2      44638 OcnA-S116…        81.7 F                  4.2                  3.5
 3      47448 FrScA-S21…        88.5 M                  5                    4  
 4      47979 OcnA-S216…        81.9 M                  5                    3.5
 5      48797 PhysA-S11…        84   F                  3.8                  3.5
 6      51943 FrScA-S21…        NA   F                  4.6                  4  
 7      52326 AnPhA-S21…        83.6 M                  5                    3.5
 8      52446 PhysA-S11…        97.8 F                  3                    3  
 9      53447 FrScA-S11…        96.1 F                  4.2                  3  
10      53475 FrScA-S11…        NA   M                 NA                   NA  
# ℹ 593 more rows
# ℹ 12 more variables: utility_value &lt;dbl&gt;, q1 &lt;dbl&gt;, q2 &lt;dbl&gt;, q3 &lt;dbl&gt;,
#   q4 &lt;dbl&gt;, q5 &lt;dbl&gt;, q6 &lt;dbl&gt;, q7 &lt;dbl&gt;, q8 &lt;dbl&gt;, q9 &lt;dbl&gt;, q10 &lt;dbl&gt;,
#   at_risk &lt;fct&gt;</code></pre>
</div>
</div>
<p><strong>Note:</strong> Be sure to pay attention to the fact that in addition to assigning our modified <code>gender</code> variable to a variable of the same name using the <code>=</code> operator, we also assigned our modified <code>course_data</code> to an object of the same name using the <code>&lt;-</code> operator. That is, we effectively overwrite the old <code>course_data</code> that included <code>gender</code> stored as a character data type to a new <code>course_data</code> object with <code>gender</code> stored as a factor.</p>
</section>
<section id="c.-select-predictors" class="level3">
<h3 class="anchored" data-anchor-id="c.-select-predictors">c.&nbsp;Select Predictors</h3>
<p>As you’ve probably noticed, there is a lot of great information in our <code>course_data</code> - but we won’t, and shouldn’t, include all of it in our predictive model. Indeed, Estrellado et al. <span class="citation" data-cites="estrellado2020data">Estrellado et al. (<a href="#ref-estrellado2020data" role="doc-biblioref">2020</a>)</span> point out that for statistical reasons and as a good general practice, it’s better to select a few variables of interest because:</p>
<blockquote class="blockquote">
<p>At a certain point, adding more variables will <em>appear</em> to make your analysis more accurate, but will in fact obscure the truth from you.</p>
</blockquote>
<section id="your-turn-3" class="level4">
<h4 class="anchored" data-anchor-id="your-turn-3"><span style="color: green;"><strong>Your Turn</strong></span> <strong>⤵</strong></h4>
<p>Complete the code chunk below to “select” (hint, hint) <code>at_risk</code> for our outcome variable, as well as the following variables we will use in our predictive model:</p>
<ul>
<li>student_id</li>
<li>course_id</li>
<li>at_risk</li>
<li>gender</li>
<li>course_interest</li>
<li>perceived_competence</li>
<li>utility_value</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>course_data <span class="ot">&lt;-</span> course_data <span class="sc">|&gt;</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(student_id, </span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>         course_id, </span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>         at_risk, </span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>         gender, </span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>         course_interest, </span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>         perceived_competence,</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>         utility_value)</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>course_data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 603 × 7
   student_id course_id     at_risk gender course_interest perceived_competence
        &lt;dbl&gt; &lt;chr&gt;         &lt;fct&gt;   &lt;fct&gt;            &lt;dbl&gt;                &lt;dbl&gt;
 1      43146 FrScA-S216-02 no      M                  5                    4.5
 2      44638 OcnA-S116-01  no      F                  4.2                  3.5
 3      47448 FrScA-S216-01 no      M                  5                    4  
 4      47979 OcnA-S216-01  no      M                  5                    3.5
 5      48797 PhysA-S116-01 no      F                  3.8                  3.5
 6      51943 FrScA-S216-03 &lt;NA&gt;    F                  4.6                  4  
 7      52326 AnPhA-S216-01 no      M                  5                    3.5
 8      52446 PhysA-S116-01 no      F                  3                    3  
 9      53447 FrScA-S116-01 no      F                  4.2                  3  
10      53475 FrScA-S116-02 &lt;NA&gt;    M                 NA                   NA  
# ℹ 593 more rows
# ℹ 1 more variable: utility_value &lt;dbl&gt;</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="explore" class="level2">
<h2 class="anchored" data-anchor-id="explore">3. Explore</h2>
<p>As noted by Krumm et al.&nbsp;(2018), exploratory data analysis often involves some combination of data visualization and feature engineering. In Part 3, we will create a quick visualization to help us spot any issues with our data and engineer new features that we will use in our predictive models. Specifically, in Part 3 we will:</p>
<ol type="a">
<li><p><strong>Examine Outcomes</strong> by taking a quick look at <code>at_risk</code> outcome variable of interest as well as our other predictors to spot any issues that may hang up out models.</p></li>
<li><p><strong>Engineer Predictors</strong> by creating some new variables we think will be predictive of students at risk, such as performance on assignments on during the first half of the course.</p></li>
</ol>
<section id="a.-count-proportions" class="level3">
<h3 class="anchored" data-anchor-id="a.-count-proportions">a. Count proportions</h3>
<p>Before we move on to feature engineering, let’s take a quick look at the proportion of students in our final data set that were identified as at-risk. To do so, run the following code chunk to take a count of the number of students labeled “yes” or “no” of being <code>at_risk</code>, and then create a new variable called proportion that takes the number <code>n</code> of each and divides by the total number:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>course_data <span class="sc">|&gt;</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(at_risk) <span class="sc">|&gt;</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">proportion =</span> n<span class="sc">/</span><span class="fu">sum</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  at_risk     n proportion
  &lt;fct&gt;   &lt;int&gt;      &lt;dbl&gt;
1 no        465     0.771 
2 yes       108     0.179 
3 &lt;NA&gt;       30     0.0498</code></pre>
</div>
</div>
<p>As you can see, roughly 18% of students in our data set were identified as “yes” for being at risk. And since these are final grades we are working with, these student were not only at risk of failing, but did indeed fail the course. You may also notice we have a number of students with missing grades, which is something we will have to address prior to analysis.</p>
<section id="your-turn-4" class="level4">
<h4 class="anchored" data-anchor-id="your-turn-4"><span style="color: green;"><strong>Your Turn</strong></span> <strong>⤵</strong></h4>
<p>Alternatively, we could have created a quick visualization to help us get a better sense of the outcomes we are trying to predict and to spot any potential issues we might run into during analysis.</p>
<p>Complete the following code chunk to create a simple bar plot illustrating the number of students who passed, failed, or have missing data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>course_data <span class="sc">|&gt;</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> at_risk)) <span class="sc">+</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="unit-2-ml-case-study-key_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="remove-cases" class="level4">
<h4 class="anchored" data-anchor-id="remove-cases">Remove Cases</h4>
<p>As you may have noticed from the outputs above, some students do not have a final grade and some are missing survey data as well. Since the models we will be using are not designed to deal with missing data, we will need to remove cases with missing data.</p>
<p>Let’s use the <code>drop_na()</code> function also from the {dplyr} package to remove observations with missing data and reassign to our <code>course_data</code> object:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>course_data <span class="ot">&lt;-</span> course_data <span class="sc">|&gt;</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>()</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>course_data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 503 × 7
   student_id course_id     at_risk gender course_interest perceived_competence
        &lt;dbl&gt; &lt;chr&gt;         &lt;fct&gt;   &lt;fct&gt;            &lt;dbl&gt;                &lt;dbl&gt;
 1      43146 FrScA-S216-02 no      M                  5                    4.5
 2      44638 OcnA-S116-01  no      F                  4.2                  3.5
 3      47448 FrScA-S216-01 no      M                  5                    4  
 4      47979 OcnA-S216-01  no      M                  5                    3.5
 5      48797 PhysA-S116-01 no      F                  3.8                  3.5
 6      52326 AnPhA-S216-01 no      M                  5                    3.5
 7      52446 PhysA-S116-01 no      F                  3                    3  
 8      53447 FrScA-S116-01 no      F                  4.2                  3  
 9      54066 OcnA-S116-01  no      M                  4.4                  4  
10      54282 OcnA-S116-02  no      F                  3.4                  3  
# ℹ 493 more rows
# ℹ 1 more variable: utility_value &lt;dbl&gt;</code></pre>
</div>
</div>
</section>
<section id="your-turn-5" class="level4">
<h4 class="anchored" data-anchor-id="your-turn-5"><span style="color: green;"><strong>Your Turn</strong></span> <strong>⤵</strong></h4>
<p>Finally, you have probably noticed that we wrote a lot more code than necessary in order to illustrate different wrangling processes to get our data ready for analysis.</p>
<p>To reduce all the redundancy caused by demonstrating each step separately above, complete the following code below by using the new <code>|&gt;</code> or old <code>%&gt;%</code> <a href="https://medium.com/analytics-vidhya/how-to-use-the-new-pipe-in-r-4-1-f7bf748a465d">pipe operators</a> to chain the <code>mutate()</code>, <code>select()</code>, and <code>drop_na()</code> functions together to wrangle our data for analysis:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>course_data <span class="ot">&lt;-</span> processed_data <span class="sc">|&gt;</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">at_risk =</span> <span class="fu">if_else</span>(final_grade <span class="sc">&gt;=</span> <span class="fl">66.7</span>, <span class="st">"no"</span>, <span class="st">"yes"</span>), <span class="co"># </span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">at_risk =</span> <span class="fu">as_factor</span>(at_risk), <span class="co">#</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">gender =</span> <span class="fu">as_factor</span>(gender)) <span class="sc">|&gt;</span> <span class="co"># </span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(student_id, <span class="co"># </span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>         course_id, </span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>         at_risk, </span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>         gender, </span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>         course_interest, </span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>         perceived_competence,</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>         utility_value) <span class="sc">|&gt;</span></span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>() <span class="co"># </span></span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>course_data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 503 × 7
   student_id course_id     at_risk gender course_interest perceived_competence
        &lt;dbl&gt; &lt;chr&gt;         &lt;fct&gt;   &lt;fct&gt;            &lt;dbl&gt;                &lt;dbl&gt;
 1      43146 FrScA-S216-02 no      M                  5                    4.5
 2      44638 OcnA-S116-01  no      F                  4.2                  3.5
 3      47448 FrScA-S216-01 no      M                  5                    4  
 4      47979 OcnA-S216-01  no      M                  5                    3.5
 5      48797 PhysA-S116-01 no      F                  3.8                  3.5
 6      52326 AnPhA-S216-01 no      M                  5                    3.5
 7      52446 PhysA-S116-01 no      F                  3                    3  
 8      53447 FrScA-S116-01 no      F                  4.2                  3  
 9      54066 OcnA-S116-01  no      M                  4.4                  4  
10      54282 OcnA-S116-02  no      F                  3.4                  3  
# ℹ 493 more rows
# ℹ 1 more variable: utility_value &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Now inspect your data again and make sure it looks like expected:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>course_data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 503 × 7
   student_id course_id     at_risk gender course_interest perceived_competence
        &lt;dbl&gt; &lt;chr&gt;         &lt;fct&gt;   &lt;fct&gt;            &lt;dbl&gt;                &lt;dbl&gt;
 1      43146 FrScA-S216-02 no      M                  5                    4.5
 2      44638 OcnA-S116-01  no      F                  4.2                  3.5
 3      47448 FrScA-S216-01 no      M                  5                    4  
 4      47979 OcnA-S216-01  no      M                  5                    3.5
 5      48797 PhysA-S116-01 no      F                  3.8                  3.5
 6      52326 AnPhA-S216-01 no      M                  5                    3.5
 7      52446 PhysA-S116-01 no      F                  3                    3  
 8      53447 FrScA-S116-01 no      F                  4.2                  3  
 9      54066 OcnA-S116-01  no      M                  4.4                  4  
10      54282 OcnA-S116-02  no      F                  3.4                  3  
# ℹ 493 more rows
# ℹ 1 more variable: utility_value &lt;dbl&gt;</code></pre>
</div>
</div>
<p><strong>Hint:</strong> You should see a total of 503 observations and 7 variables including 1 outcome variable named <code>at_risk</code>, 1 student identifier named <code>student_id</code>.</p>
</section>
</section>
<section id="b.-feature-engineering" class="level3">
<h3 class="anchored" data-anchor-id="b.-feature-engineering">b. Feature Engineering</h3>
<p>As defined by Krumm, Means, and Bienkowski (2018) in <em>Learning Analytics Goes to School</em>:</p>
<blockquote class="blockquote">
<p><strong>Feature engineering</strong> is the process of creating new variables within a dataset, which goes above and beyond the work of recoding and rescaling variables.</p>
</blockquote>
<p>The authors note that feature engineering draws on substantive knowledge from theory or practice, experience with a particular data system, and general experience in data-intensive research. Moreover, these features can be used not only in machine learning models, but also in visualizations and tables comprising descriptive statistics.</p>
<p>Though not often discussed, feature engineering is an important element of data-intensive research that can generate new insights and improve predictive models. Indeed, <a href="https://datascienceineducation.com/c14.html">an earlier attempt</a> using this data without feature engineering predicted students’ passing (or not passing) the course with only around 75% accuracy. One goal of this case study is to improve upon these results creating by some new variable using data that we think may improve our model.</p>
<section id="student-performance-features" class="level4">
<h4 class="anchored" data-anchor-id="student-performance-features">Student Performance Features</h4>
<p>In addition to information about student gender and motivation collected prior to the course, we will also incorporate into our model student performance data on course assignments. And since we are interested in developing a predictive model that that can be used to intervene before students actually fail the course, we will develop new features based on student performance on the first 20 assignments completed during the first half of the course. Specifically, we’ll create the following three “features” from the gradebook data we imported earlier:</p>
<ul>
<li>The overall percent of points earned (<em>across</em> first 20 assignments)</li>
<li>The variability (in standard deviation units) in the percent earned (<em>between</em> assignments)</li>
<li>The number of assignments for which students earned 100% of the possible points</li>
</ul>
</section>
<section id="group-slice-data" class="level4">
<h4 class="anchored" data-anchor-id="group-slice-data">Group &amp; Slice Data</h4>
<p>The {dplyr} package has a handy <code>slice()</code> function that that allows us to select, remove, and duplicate rows in a dataset based the rows in which we specify.</p>
<p>For example, run the following code chunk to select rows 1 through 20 from our <code>grade_book</code> data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">slice</span>(grade_book, <span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20 × 5
   course_id     student_id gradebook_item         points_possible points_earned
   &lt;chr&gt;              &lt;dbl&gt; &lt;chr&gt;                            &lt;dbl&gt;         &lt;dbl&gt;
 1 AnPhA-S116-01      60186 POINTS EARNED &amp; TOTAL…               5          4.05
 2 AnPhA-S116-01      60186 WORK ATTEMPTED                      30         24   
 3 AnPhA-S116-01      60186 0.1: Message Your Ins…             105         71.7 
 4 AnPhA-S116-01      60186 0.2: Intro Assignment…             140        141.  
 5 AnPhA-S116-01      60186 0.3: Intro Assignment…               5          5   
 6 AnPhA-S116-01      60186 1.1: Quiz                            5          4   
 7 AnPhA-S116-01      60186 1.2: Quiz                           20         NA   
 8 AnPhA-S116-01      60186 1.3: Create a Living …              50         50   
 9 AnPhA-S116-01      60186 1.3: Create a Living …              10         NA   
10 AnPhA-S116-01      60186 1.4: Negative Feedbac…              50         44   
11 AnPhA-S116-01      60186 1.5: Quiz                            5          4.19
12 AnPhA-S116-01      60186 Unit 1 Assessment: Pi…               5          5   
13 AnPhA-S116-01      60186 PROGRESS CHECK 1 @ 10…              24         16   
14 AnPhA-S116-01      60186 2.1: Types of Membran…              10          9.32
15 AnPhA-S116-01      60186 2.2 - 2.3: Quiz                     10          9   
16 AnPhA-S116-01      60186 2.4 - 2.5 Quiz                      10         10   
17 AnPhA-S116-01      60186 2.6: Quiz                            5          5   
18 AnPhA-S116-01      60186 Unit 2 Assessment: Te…             443        389   
19 AnPhA-S116-01      60186 3.1: Models of the In…              10         10   
20 AnPhA-S116-01      60186 3.2 - 3.3: Quiz                      5          3   </code></pre>
</div>
</div>
<p>While this helps us retrieve the first 20 assignments for the first student, it doesn’t help us with the hundreds of other students in our data set!</p>
<p>Fortunately, the {dplyr} package also has the extremely useful <code>group_by()</code> function which allows us to perform other {tidyverse} functions like <code>slice()</code>, <code>mutate()</code>, and <code>summarize()</code> by groups that we specify as arguments.</p>
<p>For example, run the following code to <em>group</em> our data by <code>student_id</code> and <code>course_id</code> using the <code>group_by()</code> function, and then we’ll use the <code>slice()</code> function again to select the first 20 assignment, but this time for the first 20 assigments each course the student completed, instead of just the first 20 assignments for the first student:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>grade_book <span class="sc">|&gt;</span> </span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(student_id, course_id) <span class="sc">|&gt;</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12,060 × 5
# Groups:   student_id, course_id [603]
   course_id     student_id gradebook_item         points_possible points_earned
   &lt;chr&gt;              &lt;dbl&gt; &lt;chr&gt;                            &lt;dbl&gt;         &lt;dbl&gt;
 1 FrScA-S216-02      43146 POINTS EARNED &amp; TOTAL…               5            NA
 2 FrScA-S216-02      43146 WORK ATTEMPTED                      10            NA
 3 FrScA-S216-02      43146 0-1.1: Intro Assignme…               5             5
 4 FrScA-S216-02      43146 0-1.2: Intro Assignme…               5             5
 5 FrScA-S216-02      43146 0-1.3: Intro Assignme…               5             5
 6 FrScA-S216-02      43146 1-1.1: Lesson 1-1 Gra…              15            13
 7 FrScA-S216-02      43146 1-2.1: Explore a Care…              37            37
 8 FrScA-S216-02      43146 1-2.2: Explore a Care…             443           365
 9 FrScA-S216-02      43146 PROGRESS CHECK 1 @ 02…               5             5
10 FrScA-S216-02      43146 1-2.3: Lesson 1-2 Gra…               5             5
# ℹ 12,050 more rows</code></pre>
</div>
</div>
<p>You’ll notice the data have significantly different dimensions now. We’ll have to take some steps to further process our <code>grade_book</code> data. In doing so, we’ll engineer some features.</p>
</section>
<section id="your-turn-6" class="level4">
<h4 class="anchored" data-anchor-id="your-turn-6"><span style="color: green;">Your Turn</span> ⤵</h4>
<p>Now let’s create a new <code>grade_book</code> data frame using what we just learned to:</p>
<ul>
<li>group our observations by <code>student_id</code> and <code>course_id</code>;</li>
<li>slice our data frame to include only the first 20 assigments for each student in each course;</li>
<li>create a new variable called <code>percent_earned</code> that equals the <code>points_earned</code> divided by <code>points_possible</code>; and,</li>
<li>remove rows with any missing data</li>
</ul>
<p>Complete the following code chunk:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>grade_book <span class="ot">&lt;-</span> grade_book <span class="sc">|&gt;</span> </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(student_id, course_id) <span class="sc">|&gt;</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>) <span class="sc">|&gt;</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">percent_earned =</span> points_earned<span class="sc">/</span>points_possible) <span class="sc">|&gt;</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>()</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>grade_book</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10,522 × 6
# Groups:   student_id, course_id [603]
   course_id     student_id gradebook_item         points_possible points_earned
   &lt;chr&gt;              &lt;dbl&gt; &lt;chr&gt;                            &lt;dbl&gt;         &lt;dbl&gt;
 1 FrScA-S216-02      43146 0-1.1: Intro Assignme…               5           5  
 2 FrScA-S216-02      43146 0-1.2: Intro Assignme…               5           5  
 3 FrScA-S216-02      43146 0-1.3: Intro Assignme…               5           5  
 4 FrScA-S216-02      43146 1-1.1: Lesson 1-1 Gra…              15          13  
 5 FrScA-S216-02      43146 1-2.1: Explore a Care…              37          37  
 6 FrScA-S216-02      43146 1-2.2: Explore a Care…             443         365  
 7 FrScA-S216-02      43146 PROGRESS CHECK 1 @ 02…               5           5  
 8 FrScA-S216-02      43146 1-2.3: Lesson 1-2 Gra…               5           5  
 9 FrScA-S216-02      43146 2-2.1: Evidence Colle…              10           8.5
10 FrScA-S216-02      43146 2-3.1: Hair Analysis …              30          23  
# ℹ 10,512 more rows
# ℹ 1 more variable: percent_earned &lt;dbl&gt;</code></pre>
</div>
</div>
<p><strong>Note:</strong> If you completed this correctly, you should have a data frame with 10,522 observations and 6 variables.</p>
</section>
<section id="create-new-variables" class="level4">
<h4 class="anchored" data-anchor-id="create-new-variables">Create New Variables</h4>
<p>Finally, let’s create three features from the gradebook data:</p>
<ul>
<li>The overall percent of points earned</li>
<li>The variability (in standard deviation units) in the percent earned (<em>between</em> assignments)</li>
<li>The number of assignments for which students earned 100% of the possible points</li>
</ul>
<p>You can probably imagine others; you’re welcome to explore adding those, too.</p>
<p>We’ll use the <code>summarize()</code> function instead of the <code>mutate()</code> function to do this, and then we’ll select just the variables needed to join our data and :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>grade_book <span class="ot">&lt;-</span> grade_book <span class="sc">|&gt;</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">overall_percent =</span> <span class="fu">sum</span>(points_earned) <span class="sc">/</span> <span class="fu">sum</span>(points_possible),</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">variability =</span> <span class="fu">sd</span>(percent_earned),</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">n_100 =</span> <span class="fu">sum</span>(percent_earned <span class="sc">==</span> <span class="dv">1</span>)) <span class="sc">|&gt;</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(student_id, </span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>         course_id, </span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>         overall_percent, </span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>         variability, </span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>         n_100)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'student_id'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>grade_book</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 603 × 5
# Groups:   student_id [580]
   student_id course_id     overall_percent variability n_100
        &lt;dbl&gt; &lt;chr&gt;                   &lt;dbl&gt;       &lt;dbl&gt; &lt;int&gt;
 1      43146 FrScA-S216-02           0.840       0.211     9
 2      44638 OcnA-S116-01            0.560       0.235    12
 3      47448 FrScA-S216-01           0.420       0.297     5
 4      47979 OcnA-S216-01            0.713       0.204     6
 5      48797 PhysA-S116-01           0.905       0.286     9
 6      51943 FrScA-S216-03           0.936       0.172     8
 7      52326 AnPhA-S216-01           0.485       0.298     6
 8      52446 PhysA-S116-01           0.843       0.137     8
 9      53447 FrScA-S116-01           0.702       0.221     5
10      53475 FrScA-S116-02           0.706       0.173     4
# ℹ 593 more rows</code></pre>
</div>
</div>
<p>We have one last step before we can get to modeling (<code>grade_book</code>) - joining this data with all of the other data (<code>course_data</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>course_data <span class="ot">&lt;-</span> <span class="fu">inner_join</span>(course_data, grade_book)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Joining with `by = join_by(student_id, course_id)`</code></pre>
</div>
</div>
</section>
<section id="your-turn-7" class="level4">
<h4 class="anchored" data-anchor-id="your-turn-7"><span style="color: green;">Your Turn</span> ⤵</h4>
<p>Let’s talk a look at the joined data to make sure everything is looking as we intend it to. Inspect the data using the code chunk below and answer the following questions:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>course_data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 503 × 10
   student_id course_id     at_risk gender course_interest perceived_competence
        &lt;dbl&gt; &lt;chr&gt;         &lt;fct&gt;   &lt;fct&gt;            &lt;dbl&gt;                &lt;dbl&gt;
 1      43146 FrScA-S216-02 no      M                  5                    4.5
 2      44638 OcnA-S116-01  no      F                  4.2                  3.5
 3      47448 FrScA-S216-01 no      M                  5                    4  
 4      47979 OcnA-S216-01  no      M                  5                    3.5
 5      48797 PhysA-S116-01 no      F                  3.8                  3.5
 6      52326 AnPhA-S216-01 no      M                  5                    3.5
 7      52446 PhysA-S116-01 no      F                  3                    3  
 8      53447 FrScA-S116-01 no      F                  4.2                  3  
 9      54066 OcnA-S116-01  no      M                  4.4                  4  
10      54282 OcnA-S116-02  no      F                  3.4                  3  
# ℹ 493 more rows
# ℹ 4 more variables: utility_value &lt;dbl&gt;, overall_percent &lt;dbl&gt;,
#   variability &lt;dbl&gt;, n_100 &lt;int&gt;</code></pre>
</div>
</div>
<ol type="1">
<li><p>What does our data frame now have 503 observations and 10 variables?</p>
<ul>
<li>YOUR RESPONSE HERE</li>
</ul></li>
<li><p>Why did we use the <code>summarize()</code> function above instead of the <code>mutate()</code> function to create our new features?</p>
<ul>
<li>YOUR RESPONSE HERE</li>
</ul></li>
</ol>
</section>
</section>
</section>
<section id="model" class="level2">
<h2 class="anchored" data-anchor-id="model">4. MODEL</h2>
<p>Recall from our readings that there are two general types of modeling approaches: unsupervised and supervised machine learning. In Part 4, we focused on supervised learning models, which are used to quantify relationships between features (e.g., motivation and performance) and a known outcome (e.g., passing or failing a course). These models can be used for statistical inference, as illustrated in Unit 1, or prediction a we’ll illustrate in this section. Specifically, in Part 4 we will learn how to:</p>
<ol type="a">
<li><p><strong>Split Data</strong> into a training and test set that will be used to develop a predictive model.</p></li>
<li><p><strong>Create a “Recipe”</strong> for our predictive model and learn how to deal with nominal data that we would like to use as predictors.</p></li>
<li><p><strong>Fit Models</strong> to our training set using logistic regression and random forest models.</p></li>
<li><p><strong>Check Model Accuracy</strong> on our test set to see how well our model can “predict” our outcome of interest.</p></li>
</ol>
<section id="a.-split-data" class="level3">
<h3 class="anchored" data-anchor-id="a.-split-data">a. Split Data</h3>
<p>The authors of Data Science in Education Using R <span class="citation" data-cites="estrellado2020data">Estrellado et al. (<a href="#ref-estrellado2020data" role="doc-biblioref">2020</a>)</span> remind us that:</p>
<blockquote class="blockquote">
<p>At its core, machine learning is the process of “showing” your statistical model only some of the data at once and training the model to predict accurately on that training dataset (this is the “learning” part of machine learning). Then, the model as developed on the training data is shown new data - data you had all along, but hid from your computer initially - and you see how well the model that you developed on the training data performs on this new testing data. Eventually, you might use the model on entirely new data.</p>
</blockquote>
<p>It is therefore common when beginning a modeling project to <a href="https://bookdown.org/max/FES/data-splitting.html">separate the data set</a> into two partitions:</p>
<ul>
<li><p>The <em>training set</em> is used to estimate develop and compare models, feature engineering techniques, tune models, etc.</p></li>
<li><p>The <em>test set</em> is held in reserve until the end of the project, at which point there should only be one or two models under serious consideration. It is used as an unbiased source for measuring final model performance.</p></li>
</ul>
<p>There are different ways to create these partitions of the data and there is no uniform guideline for determining how much data should be set aside for testing. The proportion of data can be driven by many factors, including the size of the original pool of samples and the total number of predictors.&nbsp;</p>
<p>After you decide how much to set aside, the most common approach for actually partitioning your data is to use a random sample. For our purposes, we’ll use random sampling to select 25% for the test set and use the remainder for the training set, which are the defaults for the {<a href="https://tidymodels.github.io/rsample/">rsample</a>} package.</p>
<p>Additionally, since random sampling uses random numbers, it is important to set the random number seed. This ensures that the random numbers can be reproduced at a later time (if needed).</p>
<p>The function <code>initial_split()</code> function from the {rsample} package takes the original data and saves the information on how to make the partitions.</p>
<p>Run the following code to set the random number seed and make our initial data split:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">586</span>)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>course_split <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(course_data, </span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>                              <span class="at">strata =</span> at_risk)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note that we used the <code>strata =</code> argument, which conducts a stratified split. This ensures that, despite the imbalance we noticed in our <code>at_risk</code> variable, our training and test data sets will keep roughly the same proportions of at-risk students as in the original data.&nbsp;</p>
<section id="your-turn-8" class="level4">
<h4 class="anchored" data-anchor-id="your-turn-8"><span style="color: green;"><strong>Your Turn</strong></span> <strong>⤵</strong></h4>
<p>Type <code>course_split</code> into the code chunk below, run, and answer the question that follows?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>course_split</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;Training/Testing/Total&gt;
&lt;376/127/503&gt;</code></pre>
</div>
</div>
<ol type="1">
<li><p>How many observations should we expect to see in our training and test sets respectively?</p>
<ul>
<li>YOUR RESPONSE HERE</li>
</ul></li>
</ol>
</section>
<section id="create-a-training-and-test-set" class="level4">
<h4 class="anchored" data-anchor-id="create-a-training-and-test-set">Create a training and test set</h4>
<p>The {rsample} package has two aptly named functions for creating a training and testing data set called <code>training()</code> and <code>testing()</code> respectively.</p>
<p>Run the following code to split the data into our training and test data sets:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>train_data <span class="ot">&lt;-</span> <span class="fu">training</span>(course_split)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>test_data  <span class="ot">&lt;-</span> <span class="fu">testing</span>(course_split)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="your-turn-9" class="level4">
<h4 class="anchored" data-anchor-id="your-turn-9"><span style="color: green;"><strong>Your Turn</strong></span> <strong>⤵</strong></h4>
<p>Now take a look at the training and testing sets we just created:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>train_data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 376 × 10
   student_id course_id     at_risk gender course_interest perceived_competence
        &lt;dbl&gt; &lt;chr&gt;         &lt;fct&gt;   &lt;fct&gt;            &lt;dbl&gt;                &lt;dbl&gt;
 1      43146 FrScA-S216-02 no      M                  5                    4.5
 2      44638 OcnA-S116-01  no      F                  4.2                  3.5
 3      47448 FrScA-S216-01 no      M                  5                    4  
 4      47979 OcnA-S216-01  no      M                  5                    3.5
 5      52326 AnPhA-S216-01 no      M                  5                    3.5
 6      52446 PhysA-S116-01 no      F                  3                    3  
 7      54282 OcnA-S116-02  no      F                  3.4                  3  
 8      54434 PhysA-S116-01 no      F                  4                    3  
 9      55078 FrScA-S216-01 no      F                  4.2                  3.5
10      56152 AnPhA-S116-02 no      F                  4                    4  
# ℹ 366 more rows
# ℹ 4 more variables: utility_value &lt;dbl&gt;, overall_percent &lt;dbl&gt;,
#   variability &lt;dbl&gt;, n_100 &lt;int&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>test_data</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 127 × 10
   student_id course_id     at_risk gender course_interest perceived_competence
        &lt;dbl&gt; &lt;chr&gt;         &lt;fct&gt;   &lt;fct&gt;            &lt;dbl&gt;                &lt;dbl&gt;
 1      48797 PhysA-S116-01 no      F                  3.8                  3.5
 2      53447 FrScA-S116-01 no      F                  4.2                  3  
 3      54066 OcnA-S116-01  no      M                  4.4                  4  
 4      55140 PhysA-S116-01 no      F                  3.8                  3  
 5      57981 OcnA-S116-01  yes     F                  4.2                  3  
 6      58168 AnPhA-S216-01 no      F                  5                    5  
 7      62157 FrScA-S116-02 no      F                  4.5                  3.5
 8      62175 OcnA-S216-01  no      M                  4                    4  
 9      62752 PhysA-S116-01 no      F                  4.2                  2.5
10      64930 FrScA-T116-01 no      F                  4                    3  
# ℹ 117 more rows
# ℹ 4 more variables: utility_value &lt;dbl&gt;, overall_percent &lt;dbl&gt;,
#   variability &lt;dbl&gt;, n_100 &lt;int&gt;</code></pre>
</div>
</div>
<p>Next, recycle the code from above to check to see that the proportion of at-risk students in our training and test data are close to those in our overall <code>course_data</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>train_data <span class="sc">|&gt;</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(at_risk) <span class="sc">|&gt;</span></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">proportion =</span> n<span class="sc">/</span><span class="fu">sum</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  at_risk     n proportion
  &lt;fct&gt;   &lt;int&gt;      &lt;dbl&gt;
1 no        306      0.814
2 yes        70      0.186</code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>test_data <span class="sc">|&gt;</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(at_risk) <span class="sc">|&gt;</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">proportion =</span> n<span class="sc">/</span><span class="fu">sum</span>(n))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  at_risk     n proportion
  &lt;fct&gt;   &lt;int&gt;      &lt;dbl&gt;
1 no        103      0.811
2 yes        24      0.189</code></pre>
</div>
</div>
<p>Now answer the following questions:</p>
<ol type="1">
<li><p>Do the number of observations in each set match your expectations? Why?</p>
<ul>
<li>YOUR RESPONSE HERE</li>
</ul></li>
<li><p>Do the proportion of at-risk students in each set match your expectations? Why?</p>
<ul>
<li>YOUR RESPONSE HERE</li>
</ul></li>
</ol>
</section>
</section>
<section id="b.-create-a-recipe" class="level3">
<h3 class="anchored" data-anchor-id="b.-create-a-recipe">b. <strong>Create a Recipe</strong></h3>
<p>In this section, we introduce another tidymodels package, <a href="https://recipes.tidymodels.org/">recipes</a>, which is designed to help you prepare your data <em>before</em> training your model. Recipes are built as a series of preprocessing steps, such as:</p>
<ul>
<li><p>converting qualitative predictors to indicator variables (also known as dummy variables),</p></li>
<li><p>transforming data to be on a different scale (e.g., taking the logarithm of a variable),</p></li>
<li><p>transforming whole groups of predictors together,</p></li>
<li><p>extracting key features from raw variables (e.g., getting the day of the week out of a date variable),</p></li>
</ul>
<p>and so on. If you are familiar with R’s formula interface, a lot of this might sound familiar and like what a formula already does. Recipes can be used to do many of the same things, but they have a much wider range of possibilities.</p>
<section id="add-a-formula" class="level4">
<h4 class="anchored" data-anchor-id="add-a-formula">Add a formula</h4>
<p>To get started, let’s create a recipe for a simple logistic regression model. Before training the model, we can use a recipe to add a few predictors and conduct some preprocessing required by the model.</p>
<p>The&nbsp;<a href="https://recipes.tidymodels.org/reference/recipe.html"><code>recipe()</code>&nbsp;function</a>&nbsp;as we used it here has two arguments:</p>
<ul>
<li><p>A&nbsp;<strong>formula</strong>. Any variable on the left-hand side of the tilde (<code>~</code>) is considered the model outcome (<code>at_risk</code> in our case). On the right-hand side of the tilde are the predictors. Variables may be listed by name, or you can use the dot (<code>.</code>) to indicate all other variables as predictors.</p></li>
<li><p>The <strong>data</strong>. A recipe is associated with the data set used to create the model. This will typically be the&nbsp;<em>training</em>&nbsp;set, so&nbsp;<code>data = train_data</code>&nbsp;here. Naming a data set doesn’t actually change the data itself; it is only used to catalog the names of the variables and their types, like factors, integers, dates, etc.</p></li>
</ul>
<p>Let’s create our very first recipe using <code>at_risk</code> as our outcome variable; <code>course_interest</code> and <code>gender</code> and <code>overall_percent</code> as predictors; and <code>train_data</code> as our data to train:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>lr_recipe_1 <span class="ot">&lt;-</span> <span class="fu">recipe</span>(at_risk <span class="sc">~</span> course_interest <span class="sc">+</span> gender <span class="sc">+</span> overall_percent,</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">data =</span> train_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now let’s take a quick peek at our recipe and create a quick summary of our recipe using the <code>summary()</code> function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>lr_recipe_1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code></code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Recipe ──────────────────────────────────────────────────────────────────────</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code></code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Inputs </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Number of variables by role</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>outcome:   1
predictor: 3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lr_recipe_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
  variable        type      role      source  
  &lt;chr&gt;           &lt;list&gt;    &lt;chr&gt;     &lt;chr&gt;   
1 course_interest &lt;chr [2]&gt; predictor original
2 gender          &lt;chr [3]&gt; predictor original
3 overall_percent &lt;chr [2]&gt; predictor original
4 at_risk         &lt;chr [3]&gt; outcome   original</code></pre>
</div>
</div>
<p>You can see that our recipe has four ingredients including three predictors and 1 outcome, just as expected.</p>
</section>
<section id="create-dummy-variables" class="level4">
<h4 class="anchored" data-anchor-id="create-dummy-variables">Create Dummy Variables</h4>
<p>Because we’ll be using a simple logistic regression model, variables like <code>gender</code> will need to be coded as <a href="https://bookdown.org/max/FES/creating-dummy-variables-for-unordered-categories.html">dummy variables</a>. Dummy coding means transforming a variable with multiple categories into new variables, where each binary variable indicates the presence and absence of each category. For example, gender will be recoded to gender_f, where 1 indicates female and 0 indicates male.</p>
<p>Unlike the standard model formula methods in R, a recipe <strong>does not</strong> automatically create these dummy variables for you; you’ll need to tell your recipe to add this step. This is for two reasons. First, many models do not require&nbsp;<a href="https://bookdown.org/max/FES/categorical-trees.html">numeric predictors</a>, so dummy variables may not always be preferred. Second, recipes can also be used for purposes outside of modeling, where non-dummy versions of the variables may work better. For example, you may want to make a table or a plot with a variable as a single factor.</p>
<p>For these reasons, we need to explicitly tell recipes to create dummy variables using&nbsp;<code>step_dummy()</code>. Let’s add this to our recipe and include <code>all_nominal_predictors()</code> to tell our recipe to change all of our factor variables to dummy variables:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>lr_recipe_1 <span class="ot">&lt;-</span> </span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">recipe</span>(at_risk <span class="sc">~</span> course_interest <span class="sc">+</span> gender <span class="sc">+</span> overall_percent,</span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> train_data) <span class="sc">|&gt;</span></span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_dummy</span>(<span class="fu">all_nominal_predictors</span>())</span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a>lr_recipe_1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code></code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Recipe ──────────────────────────────────────────────────────────────────────</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code></code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Inputs </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Number of variables by role</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>outcome:   1
predictor: 3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code></code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Operations </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>• Dummy variables from: all_nominal_predictors()</code></pre>
</div>
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lr_recipe_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 4
  variable        type      role      source  
  &lt;chr&gt;           &lt;list&gt;    &lt;chr&gt;     &lt;chr&gt;   
1 course_interest &lt;chr [2]&gt; predictor original
2 gender          &lt;chr [3]&gt; predictor original
3 overall_percent &lt;chr [2]&gt; predictor original
4 at_risk         &lt;chr [3]&gt; outcome   original</code></pre>
</div>
</div>
</section>
<section id="create-a-kitchen-sink-recipe" class="level4">
<h4 class="anchored" data-anchor-id="create-a-kitchen-sink-recipe">Create a kitchen sink recipe</h4>
<p>Before training our model, let’s create a second recipe just for contrast that includes all of our predictors.</p>
<p>Run the following code to add all our predictors to our new recipe:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>lr_recipe_2 <span class="ot">&lt;-</span> </span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">recipe</span>(at_risk <span class="sc">~</span> course_interest <span class="sc">+</span> gender <span class="sc">+</span> overall_percent <span class="sc">+</span> </span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>           perceived_competence <span class="sc">+</span> utility_value <span class="sc">+</span> variability <span class="sc">+</span> n_100, </span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> train_data) <span class="sc">|&gt;</span></span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_dummy</span>(<span class="fu">all_nominal_predictors</span>())</span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-7"><a href="#cb80-7" aria-hidden="true" tabindex="-1"></a>lr_recipe_2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code></code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Recipe ──────────────────────────────────────────────────────────────────────</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code></code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Inputs </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Number of variables by role</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>outcome:   1
predictor: 7</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code></code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Operations </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>• Dummy variables from: all_nominal_predictors()</code></pre>
</div>
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lr_recipe_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 4
  variable             type      role      source  
  &lt;chr&gt;                &lt;list&gt;    &lt;chr&gt;     &lt;chr&gt;   
1 course_interest      &lt;chr [2]&gt; predictor original
2 gender               &lt;chr [3]&gt; predictor original
3 overall_percent      &lt;chr [2]&gt; predictor original
4 perceived_competence &lt;chr [2]&gt; predictor original
5 utility_value        &lt;chr [2]&gt; predictor original
6 variability          &lt;chr [2]&gt; predictor original
7 n_100                &lt;chr [2]&gt; predictor original
8 at_risk              &lt;chr [3]&gt; outcome   original</code></pre>
</div>
</div>
</section>
</section>
<section id="c.-fit-a-logistic-regression-model" class="level3">
<h3 class="anchored" data-anchor-id="c.-fit-a-logistic-regression-model">c.&nbsp;Fit a Logistic Regression Model</h3>
<p>With tidymodels, we start building a model by specifying the <em>functional form</em> of the model that we want using the <a href="https://tidymodels.github.io/parsnip/">[parsnip] package</a>. Since our outcome is binary, the model type we will use is&nbsp;“<a href="https://parsnip.tidymodels.org/reference/logistic_reg.html">logistic regression</a>”. We can declare this with <code>logistic_reg()</code> and assign to an object we will later use in our workflow:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>lr_mod <span class="ot">&lt;-</span> <span class="fu">logistic_reg</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>That is pretty underwhelming since, on its own, it doesn’t really do much. However, now that the type of model has been specified, a method for&nbsp;<em>fitting</em>&nbsp;or training the model can be stated using the&nbsp;<strong>engine</strong>.</p>
<section id="start-your-engine" class="level4">
<h4 class="anchored" data-anchor-id="start-your-engine">Start your engine</h4>
<p>The engine value is often a mash-up of different packages that can be used to fit or train the model as well as the estimation method. For example, we will use “glm” a generalized linear model for binary outcomes and default for logistic regression in the {parsnip} package.</p>
<p>Run the following code to finish specifying our model:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>lr_mod <span class="ot">&lt;-</span> </span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">logistic_reg</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"glm"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="add-to-workflow" class="level4">
<h4 class="anchored" data-anchor-id="add-to-workflow">Add to workflow</h4>
<p>We will want to use our recipes created earlier across several steps as we train and test our model. To simplify this process, we can use a&nbsp;<em>model workflow</em>, which pairs a model and recipe together.</p>
<p>This is a straightforward approach because different recipes are often needed for different models, so when a model and recipe are bundled, it becomes easier to train and test&nbsp;<em>workflows</em>.</p>
<p>We’ll use the&nbsp;{<a href="https://workflows.tidymodels.org/">workflows</a>} package from tidymodels to bundle our parsnip model (<code>lr_mod</code>) with our first recipe (<code>lr_recipe_1</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>lr_workflow <span class="ot">&lt;-</span> </span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">workflow</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(lr_mod) <span class="sc">%&gt;%</span> </span>
<span id="cb94-4"><a href="#cb94-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(lr_recipe_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="fit-model-to-training-set" class="level4">
<h4 class="anchored" data-anchor-id="fit-model-to-training-set">Fit model to training set</h4>
<p>Now that we have a single workflow that can be used to prepare the recipe and train the model from the resulting predictors, we can use the <code>fit()</code> function to fit our model to our <code>train_data</code>. And again, we set a random number seed to ensure that if we run this same code again, we will get the same results in terms of the data partition:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">586</span>)</span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-3"><a href="#cb95-3" aria-hidden="true" tabindex="-1"></a>lr_fit <span class="ot">&lt;-</span> </span>
<span id="cb95-4"><a href="#cb95-4" aria-hidden="true" tabindex="-1"></a>  lr_workflow <span class="sc">%&gt;%</span> </span>
<span id="cb95-5"><a href="#cb95-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(<span class="at">data =</span> train_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This <code>lr_fit</code> object has the finalized recipe and fitted model objects inside. To extract the model fit from the workflow, we will use the helper functions&nbsp;<code>extract_fit_parsnip()</code>. Here we pull the fitted model object then use the&nbsp;<code>broom::tidy()</code>&nbsp;function to get a tidy tibble of model coefficients:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a>lr_fit <span class="sc">%&gt;%</span> </span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">extract_fit_parsnip</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 5
  term            estimate std.error statistic p.value
  &lt;chr&gt;              &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
1 (Intercept)      -2.61       1.36     -1.92   0.0548
2 course_interest  -0.0513     0.227    -0.226  0.821 
3 overall_percent   1.56       1.16      1.35   0.177 
4 gender_F          0.113      0.295     0.384  0.701 </code></pre>
</div>
</div>
<p>Among the predictors included in our model, there are no statistically significant (i.e., p-value &lt; 0.05) relationships between our predictors and being identified as at-risk according to our definition, which doesn’t bode too well for our model but let’s proceed with testing anyways.</p>
</section>
<section id="test-the-model" class="level4">
<h4 class="anchored" data-anchor-id="test-the-model">Test the model</h4>
<p>Now that we’ve fit our model to our training data, we’re FINALLY ready to test our model on the data we set aside in the beginning. Just to recap the steps that led to this moment, however, recall that we:</p>
<ol type="1">
<li><p>identified the model to use (<code>lr_mod</code>);</p></li>
<li><p>created a preprocessing recipe consisting or predictors and outcome (<code>lr_recipe_1</code>);</p></li>
<li><p>bundled the model and recipe into a workflow (<code>lr_workflow</code>); and</p></li>
<li><p>trained our workflow using a single call to&nbsp;<code>fit()</code>.</p></li>
</ol>
<p>The next step is to use the trained workflow (<code>lr_fit</code>) to predict outcomes for our unseen test data, which we will do with the function&nbsp;<code>predict()</code>. The&nbsp;<code>predict()</code>&nbsp;method applies the recipe to the new data, then passes them to the fitted model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(lr_fit, test_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 127 × 1
   .pred_class
   &lt;fct&gt;      
 1 no         
 2 no         
 3 no         
 4 no         
 5 no         
 6 no         
 7 no         
 8 no         
 9 no         
10 no         
# ℹ 117 more rows</code></pre>
</div>
</div>
<p>Because our outcome variable <code>at_risk</code> here is a factor, the output from&nbsp;<code>predict()</code>&nbsp;returns the predicted class:&nbsp;<code>no</code>&nbsp;versus&nbsp;<code>yes</code>. Not a super useful output to be honest though.</p>
<p>Fortunately there is an <code>augment()</code> function we can use with our <code>lr_fir</code> model and <code>test_data</code> to save them together:</p>
<p>Let’s use this function, save as <code>lr_predictions</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a>lr_predictions <span class="ot">&lt;-</span> <span class="fu">augment</span>(lr_fit, test_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="your-turn-10" class="level4">
<h4 class="anchored" data-anchor-id="your-turn-10"><span style="color: green;"><strong>Your Turn</strong></span> <strong>⤵</strong></h4>
<p>Take a quick look at <code>lr_predictions</code> in the code chunk below and answer the question that follows?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a>lr_predictions</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 127 × 13
   student_id course_id     at_risk gender course_interest perceived_competence
        &lt;dbl&gt; &lt;chr&gt;         &lt;fct&gt;   &lt;fct&gt;            &lt;dbl&gt;                &lt;dbl&gt;
 1      48797 PhysA-S116-01 no      F                  3.8                  3.5
 2      53447 FrScA-S116-01 no      F                  4.2                  3  
 3      54066 OcnA-S116-01  no      M                  4.4                  4  
 4      55140 PhysA-S116-01 no      F                  3.8                  3  
 5      57981 OcnA-S116-01  yes     F                  4.2                  3  
 6      58168 AnPhA-S216-01 no      F                  5                    5  
 7      62157 FrScA-S116-02 no      F                  4.5                  3.5
 8      62175 OcnA-S216-01  no      M                  4                    4  
 9      62752 PhysA-S116-01 no      F                  4.2                  2.5
10      64930 FrScA-T116-01 no      F                  4                    3  
# ℹ 117 more rows
# ℹ 7 more variables: utility_value &lt;dbl&gt;, overall_percent &lt;dbl&gt;,
#   variability &lt;dbl&gt;, n_100 &lt;int&gt;, .pred_class &lt;fct&gt;, .pred_no &lt;dbl&gt;,
#   .pred_yes &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Was our model successful at predicting any students who were at-risk? How do you know?</p>
<ul>
<li>YOUR RESPONSE HERE</li>
</ul>
<p><strong>Hint:</strong> Scroll to the end of the data frame and take a look at our original <code>at_risk</code> outcome and the <code>.pred_class</code> variable which shows the predicted outcomes.</p>
</section>
</section>
<section id="d.-check-model-accuracy" class="level3">
<h3 class="anchored" data-anchor-id="d.-check-model-accuracy">d.&nbsp;Check model accuracy</h3>
<p>As you probably noticed, just looking at the <code>lr_predictions</code> object is not the easiest way to check for model accuracy. Fortunately, the {<a href="https://tidymodels.github.io/yardstick/">yardstick}</a> package has an <code>accuracy()</code> function for looking at the overall classification accuracy, which uses the hard class predictions to measure performance.</p>
<p>Hard class predictions tell us whether our model predicted&nbsp;<code>yes</code>&nbsp;or&nbsp;<code>no</code>&nbsp;for each student in the <code>.pred_class</code> column, as well as the estimating a probability.&nbsp;A simple 50% probability cutoff is used to categorize a student as at risk. For example, student <code>47448</code> had a <code>.pred_no</code> probability of 0.8854332 and <code>.pred_yes</code> probability of 0.11456677 and so was classified as <code>no</code> for not being for <code>at_risk</code>.</p>
<p>Run the following code to <code>select()</code> these variables followed by the <code>accuracy()</code> function to see how frequently our prediction matched our observed data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a>lr_predictions <span class="sc">|&gt;</span></span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(at_risk, .pred_class) <span class="sc">|&gt;</span></span>
<span id="cb103-3"><a href="#cb103-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">accuracy</span>(<span class="at">truth =</span> at_risk, .pred_class)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  .metric  .estimator .estimate
  &lt;chr&gt;    &lt;chr&gt;          &lt;dbl&gt;
1 accuracy binary         0.811</code></pre>
</div>
</div>
<p>Overall it looks like our model was correct 81% of the time, which is not too bad but we’ll see in a second is not good enough to serve it’s intended purpose of identifying at-risk students.</p>
<p>Another way to check model accuracy is with the <code>conf_mat()</code> function from {yardstick} for creating a confusion matrix. Recall from our course text Learning Analytics Goes to School that a confusion matrix is simply a 2 × 2 table that lists the number of true-negatives, false-negatives, true-positives, and false-positives.</p>
<p>Run the follow code to create a confusion matrix for our logistic regression predictions:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a>lr_predictions <span class="sc">%&gt;%</span></span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a><span class="fu">conf_mat</span>(at_risk, .pred_class)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          Truth
Prediction  no yes
       no  103  24
       yes   0   0</code></pre>
</div>
</div>
<p>As you can see our model accurately predicted all students as “no” for at risk 103 times, but inaccurately predicted 24 students a “no” for at risk when they were actually “yes” in our <code>test_data</code>. Overall our model was 81% (103/127) accurate, but it achieved this by simply labeling everyone as “no” for at risk. And since roughly 82% of our students were actually “no,” this is clearly not a great prediction model.</p>
<section id="your-turn-11" class="level4">
<h4 class="anchored" data-anchor-id="your-turn-11"><span style="color: green;"><strong>Your Turn</strong></span> <strong>⤵</strong></h4>
<p>Recycle our code from above to create a workflow for <code>lr_recipe_2</code> and test our “kitchen sink” model on our test data. <strong>Hint:</strong> You can accomplish this by simply copying and pasting and changing a single character from above.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create workflow</span></span>
<span id="cb107-2"><a href="#cb107-2" aria-hidden="true" tabindex="-1"></a>lr_workflow <span class="ot">&lt;-</span> </span>
<span id="cb107-3"><a href="#cb107-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">workflow</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb107-4"><a href="#cb107-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(lr_mod) <span class="sc">%&gt;%</span> </span>
<span id="cb107-5"><a href="#cb107-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(lr_recipe_2)</span>
<span id="cb107-6"><a href="#cb107-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb107-7"><a href="#cb107-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb107-8"><a href="#cb107-8" aria-hidden="true" tabindex="-1"></a><span class="co"># set seeed</span></span>
<span id="cb107-9"><a href="#cb107-9" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">586</span>)</span>
<span id="cb107-10"><a href="#cb107-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb107-11"><a href="#cb107-11" aria-hidden="true" tabindex="-1"></a><span class="co"># fit model to workflow</span></span>
<span id="cb107-12"><a href="#cb107-12" aria-hidden="true" tabindex="-1"></a>lr_fit <span class="ot">&lt;-</span> </span>
<span id="cb107-13"><a href="#cb107-13" aria-hidden="true" tabindex="-1"></a>  lr_workflow <span class="sc">%&gt;%</span> </span>
<span id="cb107-14"><a href="#cb107-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(<span class="at">data =</span> train_data)</span>
<span id="cb107-15"><a href="#cb107-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb107-16"><a href="#cb107-16" aria-hidden="true" tabindex="-1"></a><span class="co"># extract model estimates</span></span>
<span id="cb107-17"><a href="#cb107-17" aria-hidden="true" tabindex="-1"></a>lr_fit <span class="sc">%&gt;%</span> </span>
<span id="cb107-18"><a href="#cb107-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">extract_fit_parsnip</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb107-19"><a href="#cb107-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 5
  term                 estimate std.error statistic p.value
  &lt;chr&gt;                   &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
1 (Intercept)           -4.51      1.85     -2.43    0.0149
2 course_interest       -0.528     0.323    -1.64    0.102 
3 overall_percent        1.49      1.30      1.15    0.251 
4 perceived_competence   0.224     0.283     0.792   0.428 
5 utility_value          0.541     0.259     2.09    0.0370
6 variability            0.155     2.41      0.0643  0.949 
7 n_100                  0.136     0.0642    2.11    0.0344
8 gender_F               0.0840    0.300     0.280   0.779 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="co"># get predictions </span></span>
<span id="cb109-2"><a href="#cb109-2" aria-hidden="true" tabindex="-1"></a>lr_predictions <span class="ot">&lt;-</span> <span class="fu">augment</span>(lr_fit, test_data)</span>
<span id="cb109-3"><a href="#cb109-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb109-4"><a href="#cb109-4" aria-hidden="true" tabindex="-1"></a><span class="co"># check overall accuracy </span></span>
<span id="cb109-5"><a href="#cb109-5" aria-hidden="true" tabindex="-1"></a>lr_predictions <span class="sc">%&gt;%</span></span>
<span id="cb109-6"><a href="#cb109-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(at_risk, .pred_class) <span class="sc">%&gt;%</span></span>
<span id="cb109-7"><a href="#cb109-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">accuracy</span>(<span class="at">truth =</span> at_risk, .pred_class)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  .metric  .estimator .estimate
  &lt;chr&gt;    &lt;chr&gt;          &lt;dbl&gt;
1 accuracy binary         0.811</code></pre>
</div>
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create a confusion matrix</span></span>
<span id="cb111-2"><a href="#cb111-2" aria-hidden="true" tabindex="-1"></a>lr_predictions <span class="sc">%&gt;%</span></span>
<span id="cb111-3"><a href="#cb111-3" aria-hidden="true" tabindex="-1"></a><span class="fu">conf_mat</span>(at_risk, .pred_class)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          Truth
Prediction  no yes
       no  103  24
       yes   0   0</code></pre>
</div>
</div>
<p>Does this model perform any better? How do you know?</p>
<ul>
<li>YOUR RESPONSE HERE</li>
</ul>
</section>
</section>
<section id="d.-fit-a-random-forest-model" class="level3">
<h3 class="anchored" data-anchor-id="d.-fit-a-random-forest-model">d.&nbsp;Fit a Random Forest Model</h3>
<p><a href="https://en.wikipedia.org/wiki/Random_forest">Random forest models</a> are&nbsp;<a href="https://en.wikipedia.org/wiki/Ensemble_learning">ensembles</a> of <a href="https://en.wikipedia.org/wiki/Decision_tree">decision trees</a>. Each of those terms is linked because there is a dense amount of information required to understand what each of those terms really means. For now, however, them main thing to know is that:</p>
<blockquote class="blockquote">
<p>One of the benefits of a random forest model is that it is very low maintenance; it requires very little preprocessing of the data and the default parameters tend to give reasonable results.</p>
</blockquote>
<p>We’ll also be using the {ranger} pacakage which provides a fast implementation of Random Forest models and is particularly suited for high dimensional data, e.g., models with a lot of predictors and features. This package supports supervised learning approaches including classification, regression, survival and probability prediction.</p>
<p>Let’s create a recipe for our <code>course_data</code>&nbsp;data that includes all our predictors.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ranger)</span>
<span id="cb113-2"><a href="#cb113-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-3"><a href="#cb113-3" aria-hidden="true" tabindex="-1"></a>rf_recipe <span class="ot">&lt;-</span> </span>
<span id="cb113-4"><a href="#cb113-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">recipe</span>(at_risk <span class="sc">~</span> gender <span class="sc">+</span> course_interest <span class="sc">+</span> perceived_competence <span class="sc">+</span> </span>
<span id="cb113-5"><a href="#cb113-5" aria-hidden="true" tabindex="-1"></a>           utility_value <span class="sc">+</span> variability <span class="sc">+</span> n_100 <span class="sc">+</span> overall_percent, </span>
<span id="cb113-6"><a href="#cb113-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">data =</span> train_data)</span>
<span id="cb113-7"><a href="#cb113-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb113-8"><a href="#cb113-8" aria-hidden="true" tabindex="-1"></a>rf_recipe</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code></code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Recipe ──────────────────────────────────────────────────────────────────────</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code></code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Inputs </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Number of variables by role</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>outcome:   1
predictor: 7</code></pre>
</div>
<div class="sourceCode cell-code" id="cb120"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb120-1"><a href="#cb120-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(rf_recipe)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 4
  variable             type      role      source  
  &lt;chr&gt;                &lt;list&gt;    &lt;chr&gt;     &lt;chr&gt;   
1 gender               &lt;chr [3]&gt; predictor original
2 course_interest      &lt;chr [2]&gt; predictor original
3 perceived_competence &lt;chr [2]&gt; predictor original
4 utility_value        &lt;chr [2]&gt; predictor original
5 variability          &lt;chr [2]&gt; predictor original
6 n_100                &lt;chr [2]&gt; predictor original
7 overall_percent      &lt;chr [2]&gt; predictor original
8 at_risk              &lt;chr [3]&gt; outcome   original</code></pre>
</div>
</div>
<p>To fit a random forest model on the training set, we’ll use the&nbsp;{<a href="https://tidymodels.github.io/parsnip/">parsnip</a>} package again along with the <a href="https://cran.r-project.org/web/packages/ranger/index.html">ranger</a> engine. We’ll also include the <code>set_mode()</code> function to specify our model as “classification” rather than “regression.”</p>
<p>Recall from our Learning Analytics Goes to School that supervised machined learning, or predictive modeling, involves two broad approaches: classification and regression. Classification algorithms model categorical outcomes (e.g., yes or no outcomes like with our at risk data). Regression algorithms characterize continuous outcomes (e.g., test scores).</p>
<p>Run the following code to create our random forest model for our training data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb122"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb122-1"><a href="#cb122-1" aria-hidden="true" tabindex="-1"></a>rf_mod <span class="ot">&lt;-</span> </span>
<span id="cb122-2"><a href="#cb122-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rand_forest</span>(<span class="at">trees =</span> <span class="dv">5000</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb122-3"><a href="#cb122-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"ranger"</span>, <span class="at">importance =</span> <span class="st">"impurity"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb122-4"><a href="#cb122-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_mode</span>(<span class="st">"classification"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now let’s combine our model and recipe to create our new random forest workflow:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb123"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb123-1"><a href="#cb123-1" aria-hidden="true" tabindex="-1"></a>rf_workflow <span class="ot">&lt;-</span> </span>
<span id="cb123-2"><a href="#cb123-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">workflow</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb123-3"><a href="#cb123-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(rf_mod) <span class="sc">%&gt;%</span> </span>
<span id="cb123-4"><a href="#cb123-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_recipe</span>(rf_recipe)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>And fit our model and recipe to our training data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb124"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb124-1"><a href="#cb124-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">586</span>)</span>
<span id="cb124-2"><a href="#cb124-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb124-3"><a href="#cb124-3" aria-hidden="true" tabindex="-1"></a>rf_fit <span class="ot">&lt;-</span> </span>
<span id="cb124-4"><a href="#cb124-4" aria-hidden="true" tabindex="-1"></a>  rf_workflow <span class="sc">%&gt;%</span> </span>
<span id="cb124-5"><a href="#cb124-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fit</span>(<span class="at">data =</span> train_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Gather our random forest predictions:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb125"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb125-1"><a href="#cb125-1" aria-hidden="true" tabindex="-1"></a>rf_predictions <span class="ot">&lt;-</span> <span class="fu">augment</span>(rf_fit, test_data)</span>
<span id="cb125-2"><a href="#cb125-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb125-3"><a href="#cb125-3" aria-hidden="true" tabindex="-1"></a>rf_predictions</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 127 × 13
   student_id course_id     at_risk gender course_interest perceived_competence
        &lt;dbl&gt; &lt;chr&gt;         &lt;fct&gt;   &lt;fct&gt;            &lt;dbl&gt;                &lt;dbl&gt;
 1      48797 PhysA-S116-01 no      F                  3.8                  3.5
 2      53447 FrScA-S116-01 no      F                  4.2                  3  
 3      54066 OcnA-S116-01  no      M                  4.4                  4  
 4      55140 PhysA-S116-01 no      F                  3.8                  3  
 5      57981 OcnA-S116-01  yes     F                  4.2                  3  
 6      58168 AnPhA-S216-01 no      F                  5                    5  
 7      62157 FrScA-S116-02 no      F                  4.5                  3.5
 8      62175 OcnA-S216-01  no      M                  4                    4  
 9      62752 PhysA-S116-01 no      F                  4.2                  2.5
10      64930 FrScA-T116-01 no      F                  4                    3  
# ℹ 117 more rows
# ℹ 7 more variables: utility_value &lt;dbl&gt;, overall_percent &lt;dbl&gt;,
#   variability &lt;dbl&gt;, n_100 &lt;int&gt;, .pred_class &lt;fct&gt;, .pred_no &lt;dbl&gt;,
#   .pred_yes &lt;dbl&gt;</code></pre>
</div>
</div>
<p>And check our model’s overall accuracy:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb127"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1" aria-hidden="true" tabindex="-1"></a>rf_predictions <span class="sc">%&gt;%</span></span>
<span id="cb127-2"><a href="#cb127-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(at_risk, .pred_class) <span class="sc">%&gt;%</span></span>
<span id="cb127-3"><a href="#cb127-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">accuracy</span>(<span class="at">truth =</span> at_risk, .pred_class)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  .metric  .estimator .estimate
  &lt;chr&gt;    &lt;chr&gt;          &lt;dbl&gt;
1 accuracy binary         0.811</code></pre>
</div>
</div>
<p>And create a confusion matrix to see where it did and did not make accurate predictions:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb129"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb129-1"><a href="#cb129-1" aria-hidden="true" tabindex="-1"></a>rf_predictions <span class="sc">|&gt;</span></span>
<span id="cb129-2"><a href="#cb129-2" aria-hidden="true" tabindex="-1"></a><span class="fu">conf_mat</span>(at_risk, .pred_class)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          Truth
Prediction  no yes
       no  102  23
       yes   1   1</code></pre>
</div>
</div>
<p>Unfortunately, our random forest model wasn’t much better at predicting students who were defined as “at risk.”</p>
<p>Even more unfortunate, if this had been a real-world situation, only 1 of the 24 students who failed the course would have received additional support. Clearly we’d need to build a better model. In this case, more data would definitely help, but it’s likely we’re missing some important information about students that is predictive of their success.</p>
<section id="your-turn-12" class="level4">
<h4 class="anchored" data-anchor-id="your-turn-12"><span style="color: green;"><strong>Your Turn</strong></span> <strong>⤵</strong></h4>
<p>Try creating your own recipe and logistic regression or random forest model and see how it performs against the three that we just created. Feel free to experiment with variables we excluded, like specific survey items. There is also a file in your data folder called&nbsp;<code>sci-mo-with-text.csv</code>&nbsp;that includes data about students participation in discussion forums, including the number of posts and psychometric properties about their language used. You can read more about that data in&nbsp;<a href="https://datascienceineducation.com/c14.html#data-sources-3">Chapter 14 of DSIEUR</a>.</p>
<p>I recommend creating and using an R script to develop your model. Use the code chunk below to record your final model:</p>
<p>Now answer the following questions?</p>
<ol type="1">
<li><p>How did your model do compared to others?</p>
<ul>
<li>YOUR RESPONSE HERE</li>
</ul></li>
<li><p>What information might be useful to know about students prior to the course start that might be useful for improving our mode?</p>
<ul>
<li>YOUR RESPONSE HERE</li>
</ul></li>
</ol>
</section>
</section>
</section>
<section id="communicate" class="level2">
<h2 class="anchored" data-anchor-id="communicate">5. COMMUNICATE</h2>
<p>In this case study, we focused applying some basic machine learning techniques to help us understand how a predictive model used in early warning systems might actually be developed and tested. Specifically, we made a very crude first attempt at developing a model using machine learning techniques that were not terribly great at accurately predict whether a student is likely to pass or fail and online course.</p>
<p>Below, add a few notes in response to the following prompts:</p>
<ol type="1">
<li><p>One thing I took away from this learning lab that I found especially useful:</p>
<ul>
<li>YOUR RESPONSE HERE</li>
</ul></li>
<li><p>One thing I want to learn more about:</p>
<ul>
<li>YOUR RESPONSE HERE</li>
</ul></li>
</ol>
<p>To “turn in” your work, you can click the “Knit” icon at the top of the file, or click the dropdown arrow next to it and select “Knit top HTML”. This will create a report in your Files pane that serves as a record of your completed assignment and that be opened in a browser or shared on the web.</p>
<section id="congratulations" class="level3 unnumbered">


</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">Congratulations!</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-estrellado2020data" class="csl-entry" role="listitem">
Estrellado, Ryan A, Emily Freer, Jesse Mostipak, Joshua M Rosenberg, and Isabella C Velásquez. 2020. <em>Data Science in Education Using r</em>. Routledge.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>