---
title: "Unit 2 Tutorials: Data Viz & Data Products"
subtitle: "ECI 586 Intro to Learning Analytics"
author: "Dr. Shaun Kellogg"
date: "`r format(Sys.Date(),'%B %e, %Y')`"
format:
  html:
    toc: true
    toc-depth: 3
theme:
  light: simplex
  dark: cyborg
editor: visual
---

### **Overview**

For Unit 2, we'll take a deeper dive into exploring and tidying our data. The assigned Visualize Data primer and corresponding exercises are designed to increase your comfort level with the {ggplot} package and useful chart types for examining single variables of interest and relationships between variables. In the tutorials that follow, you will learn how to make each type of plot show below, as well as how to use best practices and advanced skills when visualizing data. These skills we'll put to immediate use to create our first "data product" to help inform educators and/or students.

### **Primers**

For Week 6, you have two required primers to complete before we dig into our Unit 3 case study:

1.  [**Visualize Data**](https://rstudio.cloud/learn/primers/3)**:** For our third primer, we'll learn some new ggplot2 "grammar" for making new types of plots and best practices for visualizing patterns within values and relationships between variables. This primer is critical for completing your exercises and "data product" for this week so do not skip.

2.  [**Report Reproducibility**](https://rmarkdown.rstudio.com/lesson-1.html)**:** This week you'll be asked to make your first "data product" (see below) by creating a R Markdown document that you will export to an HTML webpage. Read through each of the brief sections of this primer and feel free to explore some of the external links and examples shown. Later in the course, we will be introduced to Quarto, an open-source scientific and technical publishing system and a likely successor to R markdown.

## Assessment

### **Exercises (3 points)**

We're keeping things pretty light this week on the exercise front. There is just one file to work through and five relatively simple exercises to complete, the first of which has been done for you. The final exercise in this set will be slightly more intensive and necessary to complete your data product for this week. 

1.  [**Week 6 Exercises**](https://rstudio.cloud/spaces/161268/join?access_code=24%2F%2BWGo98hxbbXotQF4UVc3dmxEZv3AjPjnRcoQu)**:** Navigate to our ECI 586 - Intro to LA RStudio Cloud workspace and complete the unit-2-visualize-exercises.R file located in the Unit 2 - Week 6 Exercises project. For the final exercise, you will be asked to create a new R Markdown file

### **Data Product (3 points)**

As highlighted in our course reading from Learning Analytics Goes to school, the Communicate step in the data-intensive research workflow is sharing the results of analysis with wider audience. Krumm et al. (2018) outlined the following 3-step process for communicating with education stakeholders what you have learned through analysis:

1.  **Select**. Communicating what one has learned involves selecting among those analyses that are most important and most useful to an intended audience, as well as selecting a form for displaying that information, such as a graph or table in static or interactive form (i.e. a "data product") and a format for communicating your results (e.g. a presentation, document, or dashboard).  

2.  **Polish**. After creating initial versions of data products, research teams often spend time refining or polishing them, by adding or editing titles, labels, and notations and by working with colors and shapes to highlight key points.

3.  **Narrate**. Writing a narrative to accompany the data products involves, at a minimum, pairing a data product with its related research question, describing how best to interpret the data product, and explaining the ways in which the data product helps answer the research question.

For exercise 6, you will be asked to select and polish a data visualization and provided instructions to create an R Markdown file you will use to share your data product along with a brief narrative. You may use the data-product-example.Rmd located in your project files pane as a template and you can find and example of the final knitted document here: <https://sbkellogg.github.io/eci-586/unit-2/data-product-example.html>\
\
When you are finished knitting your document, create a new forum post below to share your data product. You may use [RPubs](https://rpubs.com/about/getting-started) (recommended for beginners) or another service like GitHub (see above link) to publish your final knitted .html file to the web. From there you can copy the link to include in your forum post for others to access. See example post.

If you have questions about the tutorials or exercises, I encourage you to post to the forum troubleshooting post below, especially if others might benefit from the response to question. You are also more than welcome to respond to the questions posted by your peers. However, I do ask that you try work through the exercises independently before reaching out for support.
