---
title: "Final Project: Independent Analysis & Data Product"
subtitle: "ECI 586 Intro to Learning Analytics"
author: "Dr. Shaun Kellogg"
date: "`r format(Sys.Date(),'%B %e, %Y')`"
format:
  html:
    toc: true
    toc-depth: 3
theme:
  light: simplex
  dark: cyborg
editor: visual
---

## Overview

For the end-of-course project, you'll be applying the knowledge and skills gained throughout this semester to conduct the independent analysis proposed during Week 13. Similar to the case studies provided in this course, your analysis should demonstrate your ability to wrangle, analyze, and communicate findings in response to a research question of interest. You will also be expected to use [R Markdown](https://bookdown.org/yihui/rmarkdown/) (or [Quarto](https://quarto.org) if preferred) to create a reproducible data product (e.g., slide show, dashboard, report, mini "case study", etc.), which contains all the code used during each step of your analysis so it can be reproduced by others.

When you are ready to share your final data product, please click "Add a new discussion topic" to create a new forum post. In your post, include a link to your published data product, and if you worked in RStudio desktop, also attach or link to your associated R markdown file use to create you case study. If your data is sensitive or proprietary and not suitable for including in your post, please let me know.

## Grading Criteria

Grading criteria for your final project is guided by the Data-Intensive Research Workflow from [Learning analytics goes to school: A collaborative approach to improving education](https://catalog.lib.ncsu.edu/catalog/NCSU4862134) (Krumm, Means, & Bienkowski, 2018).

### Prepare

Your case study should demonstrate your ability to formulate clear, actionable research questions relevant to a targeted audience. Specifically, your case study should include an **introduction** that:

1.  Clearly describes the **purpose** of your case study, including the research question(s) guiding your analyses.

2.  Provides information about the **data sources**, including the context in which the data was collected and variables used to address your research questions.

### Wrangle

Your data project should demonstrate your ability to use R to manipulate, clean, transform, and/or merging data in order to prepare your text for analysis. Specifically, your case study should clearly describe:

3.  **Data preprocessing** steps (e.g., renaming variables, filtering, tokenization, stemming, stop words removal, etc.) taken to clean and prepare your text for analysis and why are they necessary, as well as any steps will excluded and why.

4.  Any **new variables or features** you created to address your research questions; or any data **transformations** you made required for the types of analyses or packages used (e.g. reshaping, merging, joining etc.).

### Analyze 

Your data project should demonstrate your ability to use R to apply text mining techniques appropriate to your research questions and data sources. Specifically, your case study should clearly include:

5.  Clear descriptions of the **techniques** (e.g., descriptive statistics, network analysis, sentiment analysis, etc.) you applied to analyze your data.

6.  Interpretations/meanings of specific **metrics** (e.g., counts, means, proportions, sentiment values, centrality measures, etc.) that your analysis generated. 

7.  Data **visualizations** that are attractive and easy to interpret, and include text or narrative for aiding their Interpretation by others.

### Communication

Your case study should demonstrate your ability to clearly and effectively communicate the most important and most useful findings. Specifically, your case study should:

8.  Highlights **key finding and insights** in response to your research questions. 

9.  Suggests potential **action** that you and/or your target audience to better understand and improve the context in which your data product is intended to inform.  

10. Discusses the **limitations** and any ethical/legal issues taken into consideration, including acknowledgments any reference materials used.

## Assessment

Similar to your project planning assignment in Week 13, this assignment is worth 12 points total. You will receive 1 point (10 points total) for each of the project criteria adequately addressed by your data product, and 1 point (2 points total) for each post providing constructive feedback to two of your peers is worth.
