---
title: "Unit 3 Tutorials: Tidy Data & Dashboards"
subtitle: "ECI 586 Intro to Learning Analytics"
author: "Dr. Shaun Kellogg"
date: "`r format(Sys.Date(),'%B %e, %Y')`"
format:
  html:
    toc: true
    toc-depth: 3
theme:
  light: simplex
  dark: cyborg
editor: visual
---

## Assignment

For Unit 3 we'll take a deep dive into [Quarto](https://quarto.org/), a new open-source scientific and technical publishing system and is the next generation of [R Markdown](https://rmarkdown.rstudio.com/). Quarto can be used to create dynamic content with Python, R, Julia, and Observable and to publish reproducible, production quality articles, presentations, websites, blogs, and books in HTML, PDF, MS Word, ePub, and more. This week, you'll work through three tutorials covering the basics of creating and publishing documents with Quarto and use Quarto to create and publish your first "data product."

### Primers 

This week you have two required primers to complete before we dig into our Unit 3 case study:

1.  [**Hello Quarto**](https://quarto.org/docs/get-started/hello/rstudio.html)**:** In this tutorial, you'll review the Quarto basics of editing code and markdown and previewing the rendered document in the Viewer tab as you work.

2.  [**Computations**](https://quarto.org/docs/get-started/computations/rstudio.html): In this tutorial you'll learn how to author fully reproducible computational documents with Quarto in RStudio.

3.  [**Authoring**](https://quarto.org/docs/get-started/computations/rstudio.html): In the final tutorial, you'll learn how to author Quarto document, how to add components like table of contents, equations, citations, etc., and the various document formats you can produce with the same source code.

I have included the accompanying Quarto files for each tutorial in the Unit 3 Week 9 - Tutorials workspace on Posit Cloud.

### **Data Product**

As highlighted in *Learning Analytics Goes to School*, the Communicate step in the data-intensive research workflow consists of sharing the results of analysis with wider audience. Krumm et al. (2018) outlined the following 3-step process for communicating with education stakeholders what you have learned through analysis:

-   **Select**. Communicating what one has learned involves selecting among those analyses that are most important and most useful to an intended audience, as well as selecting a form for displaying that information, such as a graph or table in static or interactive form (i.e. a "data product") and a format for communicating your results (e.g. a presentation, document, or dashboard).  

-   **Polish**. After creating initial versions of data products, research teams often spend time refining or polishing them, by adding or editing titles, labels, and notations and by working with colors and shapes to highlight key points.

-   **Narrate**. Writing a narrative to accompany the data products involves, at a minimum, pairing a data product with its related research question, describing how best to interpret the data product, and explaining the ways in which the data product helps answer the research question.

This week, you will create a new Quarto file that you will use to make and share your own data visualization. I have included some data set for you to use to create your own visualization, but you are also to use and datasets built into R or that you find online. You may use the `data-product-example.qmd` located in your project files pane as a template and you can find and example of the final knitted document published on: 

-   **GitHub** - <https://sbkellogg.github.io/eci-586/unit-2/data-product-example.html>

-   **RPubs** - <http://rpubs.com/sbkellogg/grades-time>

When you are finished knitting your HTML document, create a new post in the Week 6 forum to share your data product. You may use [RPubs](https://rpubs.com/about/getting-started) (recommended for beginners) or another service like [GitHub Pages](https://pages.github.com/) (advanced) to publish your final knitted .html file to the web. From there you can copy the link to include in your forum post for others to access. An example post has been provided.

### Peer Feedback (3 points)

Finally, provide some brief but constructive feedback (2-3 sentences) on the data products of 3 of your peers (1 point each). Your feedback should include one thing you liked about their data product and why as well as one suggestion for potential improvement or extension of the analysis.

If you have questions about the primers or dashboard, I encourage you to reply to the Questions and Troubleshooting post, especially if others might benefit from the response to question. You are also more than welcome to respond to the questions posted by your peers. However, I do ask that you try work through the exercises independently before reaching out for support.
