---
title: "Unit 3 Readings: Collaborative Research & Text as Data"
subtitle: "ECI 586 Intro to Learning Analytics"
author: "Dr. Shaun Kellogg"
date: "`r format(Sys.Date(),'%B %e, %Y')`"
format:
  html:
    toc: true
    toc-depth: 3
theme:
  light: simplex
  dark: cyborg
editor: visual
---

## OVERVIEW

In Unit 3 we examine the foundations of the collaborative data-intensive improvement (CDI) model and get a gentle introduction to working with documents and text as data. The required and self-selected readings for this week focus on three major influences on the CDI model and also provide a survey of general overview of text mining in education. In addition, we'll take a look a three broad approaches to analyzing text as data including lexical-based methods, supervised and unsupervised machine learning.

## READINGS

In addition to watching the Unit 3 Intro video, this week you'll be required to read chapter 5 from [Learning Analytics Goes to School](https://catalog.lib.ncsu.edu/catalog/NCSU4862134), an article introducing text mining methods in education, and one self-selected journal article, conference presentation, or scholarly resource to help address our discussion questions for the week.

### Required

-   Krumm, A., Means, B., & Bienkowski, M. (2018). Chapter 5: Foundations of Collaborative Applications of Educational Data Mining and Learning Analytics. *Learning analytics goes to school: A collaborative approach to improving education*. Routledge.
-   Fesler, L., Dee, T., Baker, R., & Evans, B. (2019). Text as data methods for education research. *Journal of Research on Educational Effectiveness*, *12*(4), 707-727.

### Self-Selected Resource 

Use the [NCSU Library](https://www.lib.ncsu.edu/#articles), [Google Scholar](https://scholar.google.com/) or search engine of your choice to locate a journal article, presentation, website or other scholarly resource that addresses a topic of interest and includes one or more of the following terms or related terms:

-   text mining
-   sentiment analysis
-   topic modeling
-   text classification
-   lexical- or dictionary-based methods
-   text networks
-   term frequency - inverse document frequency

Your selection should also address one or more of the discussion topics/questions provided below. In addition, you are welcome to find less formal resources such as videos or shorter online articles to share with the class and that help us better understand this week's topics for discussion.

## DISCUSSION

In lieu of the peer interaction and discussion of course materials that normally take place "in class", you'll be asked to log in this week and engage with other members of our learning community through the course discussion forum. To help guide our discussions, we will collectively address a set of guiding questions provided in each forum. You are also welcome to add your own topics or questions for the class to discuss.

With the exception of the self-selected resource, you are not required to post to every thread or address every question raised in the discussions, particularly if you feel others in the class have thoroughly addressed the topic or questions. Our primary goal for these discussions is to collectively build our understanding of this week's topics through back-and-forth dialogue.

### Guiding Questions

#### LA Goes to School Chapter 5: Foundations of Collaborative Applications of Learning Analytics

Consider an educational context you might be interested in studying an answer one or more of the following questions:

-   What real or hypothetical context educational context are you interested in better understanding or improving through collaborative data-intensive improvement?
-   How might one of the foundational approaches described described in Chapter 5 be applied to understand or improve this context?
-   What specific characteristics, processes, and/or tools of this approach might you utilize and for what purpose?

#### Text as Data: Methods for Education Research

Reflecting on the course text and your self-selected reading, answer one or more of the following questions:

-   How might text mining be used to:
    -   expand the types of research questions that researchers can ask?
    -   improve the external validity and representativeness of research?
    -   reduce the cost of research?
-   Think about text-based data source you might be interested in analyzing.
    -   What would be considered a "document" or a single observation of text (e.g., one essay, one text message, one tweet, or one discussion board post) in the data set that you would construct and/or analyze?
    -   What research question(s) might you address through automated text analysis methods?
    -   Which of the three methods would you use to answer your question?
    -   What might you have to do to prepare your text for analysis?
    -   What do you anticipate you might find from your analysis?
-   What is one limitation of automated text analysis and how might a researcher addresses it?
-   How do researchers using these methods produce valid and/or reliable results?

#### Self-Selected Resource

Provide a brief overview of your self-selected resource that includes the following:

-   APA Citation (note: this can be easily [retrieved via Google Scholar](https://libanswers.ucmerced.edu/faq/95935))
-   What was the **purpose** of your article?
-   What **data source(s),** if any, were analyzed or discussed?
-   What collaborated data-intensive research **methods or influences**, if any, were described by your selection?
-   What specific text mining **techniques(s)** were applied or discussed in your selection?
-   If a research article, what were the key **findings** of the study?
-   Who were the intended **beneficiaries** of the work and what "change ideas" might the result imply for them?
-   Did your selection discuss any **limitations or ethical considerations** of text mining?

## ASSESSMENT

### Grading

Grading for this week is fairly lenient, provided that it's clear from your posts that you've done the required readings. Readings and discussion for each unit are worth 6 points and judged based on quantity and quality of your posts.

In term of **quantity** (3 points), you'll be expected to add at least 3 posts in addition to an overview of your Selected Resource. Your initial post should be shared by Friday to help facilitate discussion.

In terms of **quality** (3 points), your posts over the next week should provide new or insightful contributions to the division questions or topics. There is no requisite for the length of each posting, and I strongly recommend taking a look at Table 1 of [Gao's productive online discussion model](https://github.com/sbkellogg/eci-586/blob/main/unit-1/lit/Gao-productive-discussion.pdf) (summarized below) for ways to contribute to the conversation.

At minimum, your collective posts should also help us interpret or elaborate on discussion topics, questions, or ideas others have shared by "making connection to the learning materials" and should reference at some point the required video, course text and your self-selected resource.

### Productive Online Discussion Model

#### Disposition 1: Discuss to Comprehend

Actively engage in such cognitive processes as interpretation, elaboration, **making connections to** prior knowledge.

-   Interpreting or elaborating the ideas by making connection to the **learning materials**
-   Interpreting or elaborating the ideas by making connection to **personal experience**
-   Interpreting or elaborating the ideas by making connection to other **ideas, sources, or references**

#### Disposition 2: Discuss to Critique

Carefully **examine other people's views**, and be sensitive and analytical to conflicting views.

-   Building or **adding new insights or ideas** to others' posts
-   **Challenging ideas** in the texts
-   Challenging ideas in others' posts

#### Disposition 3: Discuss to Construct Knowledge

Actively **negotiate meanings**, and be ready to reconsider, refine and sometimes revise their thinking.

-   **Comparing views** from the texts or others' posts
-   Facilitating thinking and discussions by **raising questions**
-   Refining and **revising one's own view** based on the texts or others' posts

#### Disposition 4: Discuss to Share Improved Understanding

Actively **synthesize knowledge** and explicitly express improved understanding based on a review of previous discussions.

-   **Summarizing personal learning** experiences of online discussions
-   **Synthesizing content** of discussion
-   **Generating new topics** based on a review of previous discussions
